
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `customers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model customers
 * 
 */
export type customersModel = runtime.Types.Result.DefaultSelection<Prisma.$customersPayload>

export type AggregateCustomers = {
  _count: CustomersCountAggregateOutputType | null
  _avg: CustomersAvgAggregateOutputType | null
  _sum: CustomersSumAggregateOutputType | null
  _min: CustomersMinAggregateOutputType | null
  _max: CustomersMaxAggregateOutputType | null
}

export type CustomersAvgAggregateOutputType = {
  id: number | null
  customer_group_id: number | null
  branch_id: number | null
  debt_amount: runtime.Decimal | null
}

export type CustomersSumAggregateOutputType = {
  id: number | null
  customer_group_id: number | null
  branch_id: number | null
  debt_amount: runtime.Decimal | null
}

export type CustomersMinAggregateOutputType = {
  id: number | null
  customer_code: string | null
  customer_name: string | null
  phone: string | null
  email: string | null
  address: string | null
  customer_group_id: number | null
  branch_id: number | null
  debt_amount: runtime.Decimal | null
  is_active: boolean | null
  created_at: Date | null
}

export type CustomersMaxAggregateOutputType = {
  id: number | null
  customer_code: string | null
  customer_name: string | null
  phone: string | null
  email: string | null
  address: string | null
  customer_group_id: number | null
  branch_id: number | null
  debt_amount: runtime.Decimal | null
  is_active: boolean | null
  created_at: Date | null
}

export type CustomersCountAggregateOutputType = {
  id: number
  customer_code: number
  customer_name: number
  phone: number
  email: number
  address: number
  customer_group_id: number
  branch_id: number
  debt_amount: number
  is_active: number
  created_at: number
  _all: number
}


export type CustomersAvgAggregateInputType = {
  id?: true
  customer_group_id?: true
  branch_id?: true
  debt_amount?: true
}

export type CustomersSumAggregateInputType = {
  id?: true
  customer_group_id?: true
  branch_id?: true
  debt_amount?: true
}

export type CustomersMinAggregateInputType = {
  id?: true
  customer_code?: true
  customer_name?: true
  phone?: true
  email?: true
  address?: true
  customer_group_id?: true
  branch_id?: true
  debt_amount?: true
  is_active?: true
  created_at?: true
}

export type CustomersMaxAggregateInputType = {
  id?: true
  customer_code?: true
  customer_name?: true
  phone?: true
  email?: true
  address?: true
  customer_group_id?: true
  branch_id?: true
  debt_amount?: true
  is_active?: true
  created_at?: true
}

export type CustomersCountAggregateInputType = {
  id?: true
  customer_code?: true
  customer_name?: true
  phone?: true
  email?: true
  address?: true
  customer_group_id?: true
  branch_id?: true
  debt_amount?: true
  is_active?: true
  created_at?: true
  _all?: true
}

export type CustomersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which customers to aggregate.
   */
  where?: Prisma.customersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of customers to fetch.
   */
  orderBy?: Prisma.customersOrderByWithRelationInput | Prisma.customersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.customersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned customers
  **/
  _count?: true | CustomersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CustomersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CustomersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomersMaxAggregateInputType
}

export type GetCustomersAggregateType<T extends CustomersAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomers[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomers[P]>
}




export type customersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.customersWhereInput
  orderBy?: Prisma.customersOrderByWithAggregationInput | Prisma.customersOrderByWithAggregationInput[]
  by: Prisma.CustomersScalarFieldEnum[] | Prisma.CustomersScalarFieldEnum
  having?: Prisma.customersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomersCountAggregateInputType | true
  _avg?: CustomersAvgAggregateInputType
  _sum?: CustomersSumAggregateInputType
  _min?: CustomersMinAggregateInputType
  _max?: CustomersMaxAggregateInputType
}

export type CustomersGroupByOutputType = {
  id: number
  customer_code: string
  customer_name: string
  phone: string | null
  email: string | null
  address: string | null
  customer_group_id: number | null
  branch_id: number | null
  debt_amount: runtime.Decimal | null
  is_active: boolean | null
  created_at: Date | null
  _count: CustomersCountAggregateOutputType | null
  _avg: CustomersAvgAggregateOutputType | null
  _sum: CustomersSumAggregateOutputType | null
  _min: CustomersMinAggregateOutputType | null
  _max: CustomersMaxAggregateOutputType | null
}

type GetCustomersGroupByPayload<T extends customersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomersGroupByOutputType[P]>
      }
    >
  >



export type customersWhereInput = {
  AND?: Prisma.customersWhereInput | Prisma.customersWhereInput[]
  OR?: Prisma.customersWhereInput[]
  NOT?: Prisma.customersWhereInput | Prisma.customersWhereInput[]
  id?: Prisma.IntFilter<"customers"> | number
  customer_code?: Prisma.StringFilter<"customers"> | string
  customer_name?: Prisma.StringFilter<"customers"> | string
  phone?: Prisma.StringNullableFilter<"customers"> | string | null
  email?: Prisma.StringNullableFilter<"customers"> | string | null
  address?: Prisma.StringNullableFilter<"customers"> | string | null
  customer_group_id?: Prisma.IntNullableFilter<"customers"> | number | null
  branch_id?: Prisma.IntNullableFilter<"customers"> | number | null
  debt_amount?: Prisma.DecimalNullableFilter<"customers"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.BoolNullableFilter<"customers"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"customers"> | Date | string | null
  branches?: Prisma.XOR<Prisma.BranchesNullableScalarRelationFilter, Prisma.branchesWhereInput> | null
  customer_groups?: Prisma.XOR<Prisma.Customer_groupsNullableScalarRelationFilter, Prisma.customer_groupsWhereInput> | null
  debt_management?: Prisma.Debt_managementListRelationFilter
  orders?: Prisma.OrdersListRelationFilter
}

export type customersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  customer_code?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  customer_group_id?: Prisma.SortOrderInput | Prisma.SortOrder
  branch_id?: Prisma.SortOrderInput | Prisma.SortOrder
  debt_amount?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  branches?: Prisma.branchesOrderByWithRelationInput
  customer_groups?: Prisma.customer_groupsOrderByWithRelationInput
  debt_management?: Prisma.debt_managementOrderByRelationAggregateInput
  orders?: Prisma.ordersOrderByRelationAggregateInput
}

export type customersWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  customer_code?: string
  AND?: Prisma.customersWhereInput | Prisma.customersWhereInput[]
  OR?: Prisma.customersWhereInput[]
  NOT?: Prisma.customersWhereInput | Prisma.customersWhereInput[]
  customer_name?: Prisma.StringFilter<"customers"> | string
  phone?: Prisma.StringNullableFilter<"customers"> | string | null
  email?: Prisma.StringNullableFilter<"customers"> | string | null
  address?: Prisma.StringNullableFilter<"customers"> | string | null
  customer_group_id?: Prisma.IntNullableFilter<"customers"> | number | null
  branch_id?: Prisma.IntNullableFilter<"customers"> | number | null
  debt_amount?: Prisma.DecimalNullableFilter<"customers"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.BoolNullableFilter<"customers"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"customers"> | Date | string | null
  branches?: Prisma.XOR<Prisma.BranchesNullableScalarRelationFilter, Prisma.branchesWhereInput> | null
  customer_groups?: Prisma.XOR<Prisma.Customer_groupsNullableScalarRelationFilter, Prisma.customer_groupsWhereInput> | null
  debt_management?: Prisma.Debt_managementListRelationFilter
  orders?: Prisma.OrdersListRelationFilter
}, "id" | "customer_code">

export type customersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  customer_code?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  customer_group_id?: Prisma.SortOrderInput | Prisma.SortOrder
  branch_id?: Prisma.SortOrderInput | Prisma.SortOrder
  debt_amount?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.customersCountOrderByAggregateInput
  _avg?: Prisma.customersAvgOrderByAggregateInput
  _max?: Prisma.customersMaxOrderByAggregateInput
  _min?: Prisma.customersMinOrderByAggregateInput
  _sum?: Prisma.customersSumOrderByAggregateInput
}

export type customersScalarWhereWithAggregatesInput = {
  AND?: Prisma.customersScalarWhereWithAggregatesInput | Prisma.customersScalarWhereWithAggregatesInput[]
  OR?: Prisma.customersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.customersScalarWhereWithAggregatesInput | Prisma.customersScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"customers"> | number
  customer_code?: Prisma.StringWithAggregatesFilter<"customers"> | string
  customer_name?: Prisma.StringWithAggregatesFilter<"customers"> | string
  phone?: Prisma.StringNullableWithAggregatesFilter<"customers"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"customers"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"customers"> | string | null
  customer_group_id?: Prisma.IntNullableWithAggregatesFilter<"customers"> | number | null
  branch_id?: Prisma.IntNullableWithAggregatesFilter<"customers"> | number | null
  debt_amount?: Prisma.DecimalNullableWithAggregatesFilter<"customers"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.BoolNullableWithAggregatesFilter<"customers"> | boolean | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"customers"> | Date | string | null
}

export type customersCreateInput = {
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  branches?: Prisma.branchesCreateNestedOneWithoutCustomersInput
  customer_groups?: Prisma.customer_groupsCreateNestedOneWithoutCustomersInput
  debt_management?: Prisma.debt_managementCreateNestedManyWithoutCustomersInput
  orders?: Prisma.ordersCreateNestedManyWithoutCustomersInput
}

export type customersUncheckedCreateInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  customer_group_id?: number | null
  branch_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  debt_management?: Prisma.debt_managementUncheckedCreateNestedManyWithoutCustomersInput
  orders?: Prisma.ordersUncheckedCreateNestedManyWithoutCustomersInput
}

export type customersUpdateInput = {
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  branches?: Prisma.branchesUpdateOneWithoutCustomersNestedInput
  customer_groups?: Prisma.customer_groupsUpdateOneWithoutCustomersNestedInput
  debt_management?: Prisma.debt_managementUpdateManyWithoutCustomersNestedInput
  orders?: Prisma.ordersUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_group_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debt_management?: Prisma.debt_managementUncheckedUpdateManyWithoutCustomersNestedInput
  orders?: Prisma.ordersUncheckedUpdateManyWithoutCustomersNestedInput
}

export type customersCreateManyInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  customer_group_id?: number | null
  branch_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
}

export type customersUpdateManyMutationInput = {
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type customersUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_group_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CustomersListRelationFilter = {
  every?: Prisma.customersWhereInput
  some?: Prisma.customersWhereInput
  none?: Prisma.customersWhereInput
}

export type customersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type customersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customer_code?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  customer_group_id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  debt_amount?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type customersAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customer_group_id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  debt_amount?: Prisma.SortOrder
}

export type customersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customer_code?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  customer_group_id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  debt_amount?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type customersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customer_code?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  customer_group_id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  debt_amount?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type customersSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customer_group_id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  debt_amount?: Prisma.SortOrder
}

export type CustomersNullableScalarRelationFilter = {
  is?: Prisma.customersWhereInput | null
  isNot?: Prisma.customersWhereInput | null
}

export type customersCreateNestedManyWithoutBranchesInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutBranchesInput, Prisma.customersUncheckedCreateWithoutBranchesInput> | Prisma.customersCreateWithoutBranchesInput[] | Prisma.customersUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutBranchesInput | Prisma.customersCreateOrConnectWithoutBranchesInput[]
  createMany?: Prisma.customersCreateManyBranchesInputEnvelope
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
}

export type customersUncheckedCreateNestedManyWithoutBranchesInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutBranchesInput, Prisma.customersUncheckedCreateWithoutBranchesInput> | Prisma.customersCreateWithoutBranchesInput[] | Prisma.customersUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutBranchesInput | Prisma.customersCreateOrConnectWithoutBranchesInput[]
  createMany?: Prisma.customersCreateManyBranchesInputEnvelope
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
}

export type customersUpdateManyWithoutBranchesNestedInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutBranchesInput, Prisma.customersUncheckedCreateWithoutBranchesInput> | Prisma.customersCreateWithoutBranchesInput[] | Prisma.customersUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutBranchesInput | Prisma.customersCreateOrConnectWithoutBranchesInput[]
  upsert?: Prisma.customersUpsertWithWhereUniqueWithoutBranchesInput | Prisma.customersUpsertWithWhereUniqueWithoutBranchesInput[]
  createMany?: Prisma.customersCreateManyBranchesInputEnvelope
  set?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  disconnect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  delete?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  update?: Prisma.customersUpdateWithWhereUniqueWithoutBranchesInput | Prisma.customersUpdateWithWhereUniqueWithoutBranchesInput[]
  updateMany?: Prisma.customersUpdateManyWithWhereWithoutBranchesInput | Prisma.customersUpdateManyWithWhereWithoutBranchesInput[]
  deleteMany?: Prisma.customersScalarWhereInput | Prisma.customersScalarWhereInput[]
}

export type customersUncheckedUpdateManyWithoutBranchesNestedInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutBranchesInput, Prisma.customersUncheckedCreateWithoutBranchesInput> | Prisma.customersCreateWithoutBranchesInput[] | Prisma.customersUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutBranchesInput | Prisma.customersCreateOrConnectWithoutBranchesInput[]
  upsert?: Prisma.customersUpsertWithWhereUniqueWithoutBranchesInput | Prisma.customersUpsertWithWhereUniqueWithoutBranchesInput[]
  createMany?: Prisma.customersCreateManyBranchesInputEnvelope
  set?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  disconnect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  delete?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  update?: Prisma.customersUpdateWithWhereUniqueWithoutBranchesInput | Prisma.customersUpdateWithWhereUniqueWithoutBranchesInput[]
  updateMany?: Prisma.customersUpdateManyWithWhereWithoutBranchesInput | Prisma.customersUpdateManyWithWhereWithoutBranchesInput[]
  deleteMany?: Prisma.customersScalarWhereInput | Prisma.customersScalarWhereInput[]
}

export type customersCreateNestedManyWithoutCustomer_groupsInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutCustomer_groupsInput, Prisma.customersUncheckedCreateWithoutCustomer_groupsInput> | Prisma.customersCreateWithoutCustomer_groupsInput[] | Prisma.customersUncheckedCreateWithoutCustomer_groupsInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutCustomer_groupsInput | Prisma.customersCreateOrConnectWithoutCustomer_groupsInput[]
  createMany?: Prisma.customersCreateManyCustomer_groupsInputEnvelope
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
}

export type customersUncheckedCreateNestedManyWithoutCustomer_groupsInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutCustomer_groupsInput, Prisma.customersUncheckedCreateWithoutCustomer_groupsInput> | Prisma.customersCreateWithoutCustomer_groupsInput[] | Prisma.customersUncheckedCreateWithoutCustomer_groupsInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutCustomer_groupsInput | Prisma.customersCreateOrConnectWithoutCustomer_groupsInput[]
  createMany?: Prisma.customersCreateManyCustomer_groupsInputEnvelope
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
}

export type customersUpdateManyWithoutCustomer_groupsNestedInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutCustomer_groupsInput, Prisma.customersUncheckedCreateWithoutCustomer_groupsInput> | Prisma.customersCreateWithoutCustomer_groupsInput[] | Prisma.customersUncheckedCreateWithoutCustomer_groupsInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutCustomer_groupsInput | Prisma.customersCreateOrConnectWithoutCustomer_groupsInput[]
  upsert?: Prisma.customersUpsertWithWhereUniqueWithoutCustomer_groupsInput | Prisma.customersUpsertWithWhereUniqueWithoutCustomer_groupsInput[]
  createMany?: Prisma.customersCreateManyCustomer_groupsInputEnvelope
  set?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  disconnect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  delete?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  update?: Prisma.customersUpdateWithWhereUniqueWithoutCustomer_groupsInput | Prisma.customersUpdateWithWhereUniqueWithoutCustomer_groupsInput[]
  updateMany?: Prisma.customersUpdateManyWithWhereWithoutCustomer_groupsInput | Prisma.customersUpdateManyWithWhereWithoutCustomer_groupsInput[]
  deleteMany?: Prisma.customersScalarWhereInput | Prisma.customersScalarWhereInput[]
}

export type customersUncheckedUpdateManyWithoutCustomer_groupsNestedInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutCustomer_groupsInput, Prisma.customersUncheckedCreateWithoutCustomer_groupsInput> | Prisma.customersCreateWithoutCustomer_groupsInput[] | Prisma.customersUncheckedCreateWithoutCustomer_groupsInput[]
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutCustomer_groupsInput | Prisma.customersCreateOrConnectWithoutCustomer_groupsInput[]
  upsert?: Prisma.customersUpsertWithWhereUniqueWithoutCustomer_groupsInput | Prisma.customersUpsertWithWhereUniqueWithoutCustomer_groupsInput[]
  createMany?: Prisma.customersCreateManyCustomer_groupsInputEnvelope
  set?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  disconnect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  delete?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  connect?: Prisma.customersWhereUniqueInput | Prisma.customersWhereUniqueInput[]
  update?: Prisma.customersUpdateWithWhereUniqueWithoutCustomer_groupsInput | Prisma.customersUpdateWithWhereUniqueWithoutCustomer_groupsInput[]
  updateMany?: Prisma.customersUpdateManyWithWhereWithoutCustomer_groupsInput | Prisma.customersUpdateManyWithWhereWithoutCustomer_groupsInput[]
  deleteMany?: Prisma.customersScalarWhereInput | Prisma.customersScalarWhereInput[]
}

export type customersCreateNestedOneWithoutDebt_managementInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutDebt_managementInput, Prisma.customersUncheckedCreateWithoutDebt_managementInput>
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutDebt_managementInput
  connect?: Prisma.customersWhereUniqueInput
}

export type customersUpdateOneWithoutDebt_managementNestedInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutDebt_managementInput, Prisma.customersUncheckedCreateWithoutDebt_managementInput>
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutDebt_managementInput
  upsert?: Prisma.customersUpsertWithoutDebt_managementInput
  disconnect?: Prisma.customersWhereInput | boolean
  delete?: Prisma.customersWhereInput | boolean
  connect?: Prisma.customersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.customersUpdateToOneWithWhereWithoutDebt_managementInput, Prisma.customersUpdateWithoutDebt_managementInput>, Prisma.customersUncheckedUpdateWithoutDebt_managementInput>
}

export type customersCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutOrdersInput, Prisma.customersUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutOrdersInput
  connect?: Prisma.customersWhereUniqueInput
}

export type customersUpdateOneWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.customersCreateWithoutOrdersInput, Prisma.customersUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.customersCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.customersUpsertWithoutOrdersInput
  disconnect?: Prisma.customersWhereInput | boolean
  delete?: Prisma.customersWhereInput | boolean
  connect?: Prisma.customersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.customersUpdateToOneWithWhereWithoutOrdersInput, Prisma.customersUpdateWithoutOrdersInput>, Prisma.customersUncheckedUpdateWithoutOrdersInput>
}

export type customersCreateWithoutBranchesInput = {
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  customer_groups?: Prisma.customer_groupsCreateNestedOneWithoutCustomersInput
  debt_management?: Prisma.debt_managementCreateNestedManyWithoutCustomersInput
  orders?: Prisma.ordersCreateNestedManyWithoutCustomersInput
}

export type customersUncheckedCreateWithoutBranchesInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  customer_group_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  debt_management?: Prisma.debt_managementUncheckedCreateNestedManyWithoutCustomersInput
  orders?: Prisma.ordersUncheckedCreateNestedManyWithoutCustomersInput
}

export type customersCreateOrConnectWithoutBranchesInput = {
  where: Prisma.customersWhereUniqueInput
  create: Prisma.XOR<Prisma.customersCreateWithoutBranchesInput, Prisma.customersUncheckedCreateWithoutBranchesInput>
}

export type customersCreateManyBranchesInputEnvelope = {
  data: Prisma.customersCreateManyBranchesInput | Prisma.customersCreateManyBranchesInput[]
  skipDuplicates?: boolean
}

export type customersUpsertWithWhereUniqueWithoutBranchesInput = {
  where: Prisma.customersWhereUniqueInput
  update: Prisma.XOR<Prisma.customersUpdateWithoutBranchesInput, Prisma.customersUncheckedUpdateWithoutBranchesInput>
  create: Prisma.XOR<Prisma.customersCreateWithoutBranchesInput, Prisma.customersUncheckedCreateWithoutBranchesInput>
}

export type customersUpdateWithWhereUniqueWithoutBranchesInput = {
  where: Prisma.customersWhereUniqueInput
  data: Prisma.XOR<Prisma.customersUpdateWithoutBranchesInput, Prisma.customersUncheckedUpdateWithoutBranchesInput>
}

export type customersUpdateManyWithWhereWithoutBranchesInput = {
  where: Prisma.customersScalarWhereInput
  data: Prisma.XOR<Prisma.customersUpdateManyMutationInput, Prisma.customersUncheckedUpdateManyWithoutBranchesInput>
}

export type customersScalarWhereInput = {
  AND?: Prisma.customersScalarWhereInput | Prisma.customersScalarWhereInput[]
  OR?: Prisma.customersScalarWhereInput[]
  NOT?: Prisma.customersScalarWhereInput | Prisma.customersScalarWhereInput[]
  id?: Prisma.IntFilter<"customers"> | number
  customer_code?: Prisma.StringFilter<"customers"> | string
  customer_name?: Prisma.StringFilter<"customers"> | string
  phone?: Prisma.StringNullableFilter<"customers"> | string | null
  email?: Prisma.StringNullableFilter<"customers"> | string | null
  address?: Prisma.StringNullableFilter<"customers"> | string | null
  customer_group_id?: Prisma.IntNullableFilter<"customers"> | number | null
  branch_id?: Prisma.IntNullableFilter<"customers"> | number | null
  debt_amount?: Prisma.DecimalNullableFilter<"customers"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.BoolNullableFilter<"customers"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"customers"> | Date | string | null
}

export type customersCreateWithoutCustomer_groupsInput = {
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  branches?: Prisma.branchesCreateNestedOneWithoutCustomersInput
  debt_management?: Prisma.debt_managementCreateNestedManyWithoutCustomersInput
  orders?: Prisma.ordersCreateNestedManyWithoutCustomersInput
}

export type customersUncheckedCreateWithoutCustomer_groupsInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  branch_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  debt_management?: Prisma.debt_managementUncheckedCreateNestedManyWithoutCustomersInput
  orders?: Prisma.ordersUncheckedCreateNestedManyWithoutCustomersInput
}

export type customersCreateOrConnectWithoutCustomer_groupsInput = {
  where: Prisma.customersWhereUniqueInput
  create: Prisma.XOR<Prisma.customersCreateWithoutCustomer_groupsInput, Prisma.customersUncheckedCreateWithoutCustomer_groupsInput>
}

export type customersCreateManyCustomer_groupsInputEnvelope = {
  data: Prisma.customersCreateManyCustomer_groupsInput | Prisma.customersCreateManyCustomer_groupsInput[]
  skipDuplicates?: boolean
}

export type customersUpsertWithWhereUniqueWithoutCustomer_groupsInput = {
  where: Prisma.customersWhereUniqueInput
  update: Prisma.XOR<Prisma.customersUpdateWithoutCustomer_groupsInput, Prisma.customersUncheckedUpdateWithoutCustomer_groupsInput>
  create: Prisma.XOR<Prisma.customersCreateWithoutCustomer_groupsInput, Prisma.customersUncheckedCreateWithoutCustomer_groupsInput>
}

export type customersUpdateWithWhereUniqueWithoutCustomer_groupsInput = {
  where: Prisma.customersWhereUniqueInput
  data: Prisma.XOR<Prisma.customersUpdateWithoutCustomer_groupsInput, Prisma.customersUncheckedUpdateWithoutCustomer_groupsInput>
}

export type customersUpdateManyWithWhereWithoutCustomer_groupsInput = {
  where: Prisma.customersScalarWhereInput
  data: Prisma.XOR<Prisma.customersUpdateManyMutationInput, Prisma.customersUncheckedUpdateManyWithoutCustomer_groupsInput>
}

export type customersCreateWithoutDebt_managementInput = {
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  branches?: Prisma.branchesCreateNestedOneWithoutCustomersInput
  customer_groups?: Prisma.customer_groupsCreateNestedOneWithoutCustomersInput
  orders?: Prisma.ordersCreateNestedManyWithoutCustomersInput
}

export type customersUncheckedCreateWithoutDebt_managementInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  customer_group_id?: number | null
  branch_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  orders?: Prisma.ordersUncheckedCreateNestedManyWithoutCustomersInput
}

export type customersCreateOrConnectWithoutDebt_managementInput = {
  where: Prisma.customersWhereUniqueInput
  create: Prisma.XOR<Prisma.customersCreateWithoutDebt_managementInput, Prisma.customersUncheckedCreateWithoutDebt_managementInput>
}

export type customersUpsertWithoutDebt_managementInput = {
  update: Prisma.XOR<Prisma.customersUpdateWithoutDebt_managementInput, Prisma.customersUncheckedUpdateWithoutDebt_managementInput>
  create: Prisma.XOR<Prisma.customersCreateWithoutDebt_managementInput, Prisma.customersUncheckedCreateWithoutDebt_managementInput>
  where?: Prisma.customersWhereInput
}

export type customersUpdateToOneWithWhereWithoutDebt_managementInput = {
  where?: Prisma.customersWhereInput
  data: Prisma.XOR<Prisma.customersUpdateWithoutDebt_managementInput, Prisma.customersUncheckedUpdateWithoutDebt_managementInput>
}

export type customersUpdateWithoutDebt_managementInput = {
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  branches?: Prisma.branchesUpdateOneWithoutCustomersNestedInput
  customer_groups?: Prisma.customer_groupsUpdateOneWithoutCustomersNestedInput
  orders?: Prisma.ordersUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateWithoutDebt_managementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_group_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  orders?: Prisma.ordersUncheckedUpdateManyWithoutCustomersNestedInput
}

export type customersCreateWithoutOrdersInput = {
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  branches?: Prisma.branchesCreateNestedOneWithoutCustomersInput
  customer_groups?: Prisma.customer_groupsCreateNestedOneWithoutCustomersInput
  debt_management?: Prisma.debt_managementCreateNestedManyWithoutCustomersInput
}

export type customersUncheckedCreateWithoutOrdersInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  customer_group_id?: number | null
  branch_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
  debt_management?: Prisma.debt_managementUncheckedCreateNestedManyWithoutCustomersInput
}

export type customersCreateOrConnectWithoutOrdersInput = {
  where: Prisma.customersWhereUniqueInput
  create: Prisma.XOR<Prisma.customersCreateWithoutOrdersInput, Prisma.customersUncheckedCreateWithoutOrdersInput>
}

export type customersUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.customersUpdateWithoutOrdersInput, Prisma.customersUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.customersCreateWithoutOrdersInput, Prisma.customersUncheckedCreateWithoutOrdersInput>
  where?: Prisma.customersWhereInput
}

export type customersUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.customersWhereInput
  data: Prisma.XOR<Prisma.customersUpdateWithoutOrdersInput, Prisma.customersUncheckedUpdateWithoutOrdersInput>
}

export type customersUpdateWithoutOrdersInput = {
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  branches?: Prisma.branchesUpdateOneWithoutCustomersNestedInput
  customer_groups?: Prisma.customer_groupsUpdateOneWithoutCustomersNestedInput
  debt_management?: Prisma.debt_managementUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_group_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debt_management?: Prisma.debt_managementUncheckedUpdateManyWithoutCustomersNestedInput
}

export type customersCreateManyBranchesInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  customer_group_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
}

export type customersUpdateWithoutBranchesInput = {
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customer_groups?: Prisma.customer_groupsUpdateOneWithoutCustomersNestedInput
  debt_management?: Prisma.debt_managementUpdateManyWithoutCustomersNestedInput
  orders?: Prisma.ordersUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateWithoutBranchesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_group_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debt_management?: Prisma.debt_managementUncheckedUpdateManyWithoutCustomersNestedInput
  orders?: Prisma.ordersUncheckedUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateManyWithoutBranchesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_group_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type customersCreateManyCustomer_groupsInput = {
  id?: number
  customer_code: string
  customer_name: string
  phone?: string | null
  email?: string | null
  address?: string | null
  branch_id?: number | null
  debt_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: boolean | null
  created_at?: Date | string | null
}

export type customersUpdateWithoutCustomer_groupsInput = {
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  branches?: Prisma.branchesUpdateOneWithoutCustomersNestedInput
  debt_management?: Prisma.debt_managementUpdateManyWithoutCustomersNestedInput
  orders?: Prisma.ordersUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateWithoutCustomer_groupsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debt_management?: Prisma.debt_managementUncheckedUpdateManyWithoutCustomersNestedInput
  orders?: Prisma.ordersUncheckedUpdateManyWithoutCustomersNestedInput
}

export type customersUncheckedUpdateManyWithoutCustomer_groupsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_code?: Prisma.StringFieldUpdateOperationsInput | string
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  debt_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  is_active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type CustomersCountOutputType
 */

export type CustomersCountOutputType = {
  debt_management: number
  orders: number
}

export type CustomersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  debt_management?: boolean | CustomersCountOutputTypeCountDebt_managementArgs
  orders?: boolean | CustomersCountOutputTypeCountOrdersArgs
}

/**
 * CustomersCountOutputType without action
 */
export type CustomersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomersCountOutputType
   */
  select?: Prisma.CustomersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CustomersCountOutputType without action
 */
export type CustomersCountOutputTypeCountDebt_managementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.debt_managementWhereInput
}

/**
 * CustomersCountOutputType without action
 */
export type CustomersCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ordersWhereInput
}


export type customersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customer_code?: boolean
  customer_name?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  customer_group_id?: boolean
  branch_id?: boolean
  debt_amount?: boolean
  is_active?: boolean
  created_at?: boolean
  branches?: boolean | Prisma.customers$branchesArgs<ExtArgs>
  customer_groups?: boolean | Prisma.customers$customer_groupsArgs<ExtArgs>
  debt_management?: boolean | Prisma.customers$debt_managementArgs<ExtArgs>
  orders?: boolean | Prisma.customers$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.CustomersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customers"]>

export type customersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customer_code?: boolean
  customer_name?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  customer_group_id?: boolean
  branch_id?: boolean
  debt_amount?: boolean
  is_active?: boolean
  created_at?: boolean
  branches?: boolean | Prisma.customers$branchesArgs<ExtArgs>
  customer_groups?: boolean | Prisma.customers$customer_groupsArgs<ExtArgs>
}, ExtArgs["result"]["customers"]>

export type customersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customer_code?: boolean
  customer_name?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  customer_group_id?: boolean
  branch_id?: boolean
  debt_amount?: boolean
  is_active?: boolean
  created_at?: boolean
  branches?: boolean | Prisma.customers$branchesArgs<ExtArgs>
  customer_groups?: boolean | Prisma.customers$customer_groupsArgs<ExtArgs>
}, ExtArgs["result"]["customers"]>

export type customersSelectScalar = {
  id?: boolean
  customer_code?: boolean
  customer_name?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  customer_group_id?: boolean
  branch_id?: boolean
  debt_amount?: boolean
  is_active?: boolean
  created_at?: boolean
}

export type customersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "customer_code" | "customer_name" | "phone" | "email" | "address" | "customer_group_id" | "branch_id" | "debt_amount" | "is_active" | "created_at", ExtArgs["result"]["customers"]>
export type customersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  branches?: boolean | Prisma.customers$branchesArgs<ExtArgs>
  customer_groups?: boolean | Prisma.customers$customer_groupsArgs<ExtArgs>
  debt_management?: boolean | Prisma.customers$debt_managementArgs<ExtArgs>
  orders?: boolean | Prisma.customers$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.CustomersCountOutputTypeDefaultArgs<ExtArgs>
}
export type customersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  branches?: boolean | Prisma.customers$branchesArgs<ExtArgs>
  customer_groups?: boolean | Prisma.customers$customer_groupsArgs<ExtArgs>
}
export type customersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  branches?: boolean | Prisma.customers$branchesArgs<ExtArgs>
  customer_groups?: boolean | Prisma.customers$customer_groupsArgs<ExtArgs>
}

export type $customersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "customers"
  objects: {
    branches: Prisma.$branchesPayload<ExtArgs> | null
    customer_groups: Prisma.$customer_groupsPayload<ExtArgs> | null
    debt_management: Prisma.$debt_managementPayload<ExtArgs>[]
    orders: Prisma.$ordersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    customer_code: string
    customer_name: string
    phone: string | null
    email: string | null
    address: string | null
    customer_group_id: number | null
    branch_id: number | null
    debt_amount: runtime.Decimal | null
    is_active: boolean | null
    created_at: Date | null
  }, ExtArgs["result"]["customers"]>
  composites: {}
}

export type customersGetPayload<S extends boolean | null | undefined | customersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$customersPayload, S>

export type customersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<customersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomersCountAggregateInputType | true
  }

export interface customersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['customers'], meta: { name: 'customers' } }
  /**
   * Find zero or one Customers that matches the filter.
   * @param {customersFindUniqueArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends customersFindUniqueArgs>(args: Prisma.SelectSubset<T, customersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Customers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {customersFindUniqueOrThrowArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends customersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, customersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {customersFindFirstArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends customersFindFirstArgs>(args?: Prisma.SelectSubset<T, customersFindFirstArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {customersFindFirstOrThrowArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends customersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, customersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Customers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {customersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Customers
   * const customers = await prisma.customers.findMany()
   * 
   * // Get first 10 Customers
   * const customers = await prisma.customers.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customersWithIdOnly = await prisma.customers.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends customersFindManyArgs>(args?: Prisma.SelectSubset<T, customersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Customers.
   * @param {customersCreateArgs} args - Arguments to create a Customers.
   * @example
   * // Create one Customers
   * const Customers = await prisma.customers.create({
   *   data: {
   *     // ... data to create a Customers
   *   }
   * })
   * 
   */
  create<T extends customersCreateArgs>(args: Prisma.SelectSubset<T, customersCreateArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Customers.
   * @param {customersCreateManyArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customers = await prisma.customers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends customersCreateManyArgs>(args?: Prisma.SelectSubset<T, customersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Customers and returns the data saved in the database.
   * @param {customersCreateManyAndReturnArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customers = await prisma.customers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Customers and only return the `id`
   * const customersWithIdOnly = await prisma.customers.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends customersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, customersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Customers.
   * @param {customersDeleteArgs} args - Arguments to delete one Customers.
   * @example
   * // Delete one Customers
   * const Customers = await prisma.customers.delete({
   *   where: {
   *     // ... filter to delete one Customers
   *   }
   * })
   * 
   */
  delete<T extends customersDeleteArgs>(args: Prisma.SelectSubset<T, customersDeleteArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Customers.
   * @param {customersUpdateArgs} args - Arguments to update one Customers.
   * @example
   * // Update one Customers
   * const customers = await prisma.customers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends customersUpdateArgs>(args: Prisma.SelectSubset<T, customersUpdateArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Customers.
   * @param {customersDeleteManyArgs} args - Arguments to filter Customers to delete.
   * @example
   * // Delete a few Customers
   * const { count } = await prisma.customers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends customersDeleteManyArgs>(args?: Prisma.SelectSubset<T, customersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {customersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Customers
   * const customers = await prisma.customers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends customersUpdateManyArgs>(args: Prisma.SelectSubset<T, customersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers and returns the data updated in the database.
   * @param {customersUpdateManyAndReturnArgs} args - Arguments to update many Customers.
   * @example
   * // Update many Customers
   * const customers = await prisma.customers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Customers and only return the `id`
   * const customersWithIdOnly = await prisma.customers.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends customersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, customersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Customers.
   * @param {customersUpsertArgs} args - Arguments to update or create a Customers.
   * @example
   * // Update or create a Customers
   * const customers = await prisma.customers.upsert({
   *   create: {
   *     // ... data to create a Customers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Customers we want to update
   *   }
   * })
   */
  upsert<T extends customersUpsertArgs>(args: Prisma.SelectSubset<T, customersUpsertArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {customersCountArgs} args - Arguments to filter Customers to count.
   * @example
   * // Count the number of Customers
   * const count = await prisma.customers.count({
   *   where: {
   *     // ... the filter for the Customers we want to count
   *   }
   * })
  **/
  count<T extends customersCountArgs>(
    args?: Prisma.Subset<T, customersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomersAggregateArgs>(args: Prisma.Subset<T, CustomersAggregateArgs>): Prisma.PrismaPromise<GetCustomersAggregateType<T>>

  /**
   * Group by Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {customersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends customersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: customersGroupByArgs['orderBy'] }
      : { orderBy?: customersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, customersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the customers model
 */
readonly fields: customersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for customers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__customersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  branches<T extends Prisma.customers$branchesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.customers$branchesArgs<ExtArgs>>): Prisma.Prisma__branchesClient<runtime.Types.Result.GetResult<Prisma.$branchesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  customer_groups<T extends Prisma.customers$customer_groupsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.customers$customer_groupsArgs<ExtArgs>>): Prisma.Prisma__customer_groupsClient<runtime.Types.Result.GetResult<Prisma.$customer_groupsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  debt_management<T extends Prisma.customers$debt_managementArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.customers$debt_managementArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$debt_managementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.customers$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.customers$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the customers model
 */
export interface customersFieldRefs {
  readonly id: Prisma.FieldRef<"customers", 'Int'>
  readonly customer_code: Prisma.FieldRef<"customers", 'String'>
  readonly customer_name: Prisma.FieldRef<"customers", 'String'>
  readonly phone: Prisma.FieldRef<"customers", 'String'>
  readonly email: Prisma.FieldRef<"customers", 'String'>
  readonly address: Prisma.FieldRef<"customers", 'String'>
  readonly customer_group_id: Prisma.FieldRef<"customers", 'Int'>
  readonly branch_id: Prisma.FieldRef<"customers", 'Int'>
  readonly debt_amount: Prisma.FieldRef<"customers", 'Decimal'>
  readonly is_active: Prisma.FieldRef<"customers", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"customers", 'DateTime'>
}
    

// Custom InputTypes
/**
 * customers findUnique
 */
export type customersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * Filter, which customers to fetch.
   */
  where: Prisma.customersWhereUniqueInput
}

/**
 * customers findUniqueOrThrow
 */
export type customersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * Filter, which customers to fetch.
   */
  where: Prisma.customersWhereUniqueInput
}

/**
 * customers findFirst
 */
export type customersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * Filter, which customers to fetch.
   */
  where?: Prisma.customersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of customers to fetch.
   */
  orderBy?: Prisma.customersOrderByWithRelationInput | Prisma.customersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for customers.
   */
  cursor?: Prisma.customersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of customers.
   */
  distinct?: Prisma.CustomersScalarFieldEnum | Prisma.CustomersScalarFieldEnum[]
}

/**
 * customers findFirstOrThrow
 */
export type customersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * Filter, which customers to fetch.
   */
  where?: Prisma.customersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of customers to fetch.
   */
  orderBy?: Prisma.customersOrderByWithRelationInput | Prisma.customersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for customers.
   */
  cursor?: Prisma.customersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of customers.
   */
  distinct?: Prisma.CustomersScalarFieldEnum | Prisma.CustomersScalarFieldEnum[]
}

/**
 * customers findMany
 */
export type customersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * Filter, which customers to fetch.
   */
  where?: Prisma.customersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of customers to fetch.
   */
  orderBy?: Prisma.customersOrderByWithRelationInput | Prisma.customersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing customers.
   */
  cursor?: Prisma.customersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` customers.
   */
  skip?: number
  distinct?: Prisma.CustomersScalarFieldEnum | Prisma.CustomersScalarFieldEnum[]
}

/**
 * customers create
 */
export type customersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * The data needed to create a customers.
   */
  data: Prisma.XOR<Prisma.customersCreateInput, Prisma.customersUncheckedCreateInput>
}

/**
 * customers createMany
 */
export type customersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many customers.
   */
  data: Prisma.customersCreateManyInput | Prisma.customersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * customers createManyAndReturn
 */
export type customersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * The data used to create many customers.
   */
  data: Prisma.customersCreateManyInput | Prisma.customersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * customers update
 */
export type customersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * The data needed to update a customers.
   */
  data: Prisma.XOR<Prisma.customersUpdateInput, Prisma.customersUncheckedUpdateInput>
  /**
   * Choose, which customers to update.
   */
  where: Prisma.customersWhereUniqueInput
}

/**
 * customers updateMany
 */
export type customersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update customers.
   */
  data: Prisma.XOR<Prisma.customersUpdateManyMutationInput, Prisma.customersUncheckedUpdateManyInput>
  /**
   * Filter which customers to update
   */
  where?: Prisma.customersWhereInput
  /**
   * Limit how many customers to update.
   */
  limit?: number
}

/**
 * customers updateManyAndReturn
 */
export type customersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * The data used to update customers.
   */
  data: Prisma.XOR<Prisma.customersUpdateManyMutationInput, Prisma.customersUncheckedUpdateManyInput>
  /**
   * Filter which customers to update
   */
  where?: Prisma.customersWhereInput
  /**
   * Limit how many customers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * customers upsert
 */
export type customersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * The filter to search for the customers to update in case it exists.
   */
  where: Prisma.customersWhereUniqueInput
  /**
   * In case the customers found by the `where` argument doesn't exist, create a new customers with this data.
   */
  create: Prisma.XOR<Prisma.customersCreateInput, Prisma.customersUncheckedCreateInput>
  /**
   * In case the customers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.customersUpdateInput, Prisma.customersUncheckedUpdateInput>
}

/**
 * customers delete
 */
export type customersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
  /**
   * Filter which customers to delete.
   */
  where: Prisma.customersWhereUniqueInput
}

/**
 * customers deleteMany
 */
export type customersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which customers to delete
   */
  where?: Prisma.customersWhereInput
  /**
   * Limit how many customers to delete.
   */
  limit?: number
}

/**
 * customers.branches
 */
export type customers$branchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the branches
   */
  select?: Prisma.branchesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the branches
   */
  omit?: Prisma.branchesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.branchesInclude<ExtArgs> | null
  where?: Prisma.branchesWhereInput
}

/**
 * customers.customer_groups
 */
export type customers$customer_groupsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customer_groups
   */
  select?: Prisma.customer_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customer_groups
   */
  omit?: Prisma.customer_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customer_groupsInclude<ExtArgs> | null
  where?: Prisma.customer_groupsWhereInput
}

/**
 * customers.debt_management
 */
export type customers$debt_managementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_management
   */
  select?: Prisma.debt_managementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_management
   */
  omit?: Prisma.debt_managementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_managementInclude<ExtArgs> | null
  where?: Prisma.debt_managementWhereInput
  orderBy?: Prisma.debt_managementOrderByWithRelationInput | Prisma.debt_managementOrderByWithRelationInput[]
  cursor?: Prisma.debt_managementWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Debt_managementScalarFieldEnum | Prisma.Debt_managementScalarFieldEnum[]
}

/**
 * customers.orders
 */
export type customers$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  where?: Prisma.ordersWhereInput
  orderBy?: Prisma.ordersOrderByWithRelationInput | Prisma.ordersOrderByWithRelationInput[]
  cursor?: Prisma.ordersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrdersScalarFieldEnum | Prisma.OrdersScalarFieldEnum[]
}

/**
 * customers without action
 */
export type customersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the customers
   */
  select?: Prisma.customersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the customers
   */
  omit?: Prisma.customersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.customersInclude<ExtArgs> | null
}
