
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `debt_payments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model debt_payments
 * 
 */
export type debt_paymentsModel = runtime.Types.Result.DefaultSelection<Prisma.$debt_paymentsPayload>

export type AggregateDebt_payments = {
  _count: Debt_paymentsCountAggregateOutputType | null
  _avg: Debt_paymentsAvgAggregateOutputType | null
  _sum: Debt_paymentsSumAggregateOutputType | null
  _min: Debt_paymentsMinAggregateOutputType | null
  _max: Debt_paymentsMaxAggregateOutputType | null
}

export type Debt_paymentsAvgAggregateOutputType = {
  id: number | null
  debt_id: number | null
  payment_amount: runtime.Decimal | null
  bank_account_id: number | null
  created_by: number | null
}

export type Debt_paymentsSumAggregateOutputType = {
  id: number | null
  debt_id: number | null
  payment_amount: runtime.Decimal | null
  bank_account_id: number | null
  created_by: number | null
}

export type Debt_paymentsMinAggregateOutputType = {
  id: number | null
  debt_id: number | null
  payment_amount: runtime.Decimal | null
  payment_date: Date | null
  payment_method: string | null
  bank_account_id: number | null
  notes: string | null
  created_by: number | null
  created_at: Date | null
}

export type Debt_paymentsMaxAggregateOutputType = {
  id: number | null
  debt_id: number | null
  payment_amount: runtime.Decimal | null
  payment_date: Date | null
  payment_method: string | null
  bank_account_id: number | null
  notes: string | null
  created_by: number | null
  created_at: Date | null
}

export type Debt_paymentsCountAggregateOutputType = {
  id: number
  debt_id: number
  payment_amount: number
  payment_date: number
  payment_method: number
  bank_account_id: number
  notes: number
  created_by: number
  created_at: number
  _all: number
}


export type Debt_paymentsAvgAggregateInputType = {
  id?: true
  debt_id?: true
  payment_amount?: true
  bank_account_id?: true
  created_by?: true
}

export type Debt_paymentsSumAggregateInputType = {
  id?: true
  debt_id?: true
  payment_amount?: true
  bank_account_id?: true
  created_by?: true
}

export type Debt_paymentsMinAggregateInputType = {
  id?: true
  debt_id?: true
  payment_amount?: true
  payment_date?: true
  payment_method?: true
  bank_account_id?: true
  notes?: true
  created_by?: true
  created_at?: true
}

export type Debt_paymentsMaxAggregateInputType = {
  id?: true
  debt_id?: true
  payment_amount?: true
  payment_date?: true
  payment_method?: true
  bank_account_id?: true
  notes?: true
  created_by?: true
  created_at?: true
}

export type Debt_paymentsCountAggregateInputType = {
  id?: true
  debt_id?: true
  payment_amount?: true
  payment_date?: true
  payment_method?: true
  bank_account_id?: true
  notes?: true
  created_by?: true
  created_at?: true
  _all?: true
}

export type Debt_paymentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which debt_payments to aggregate.
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of debt_payments to fetch.
   */
  orderBy?: Prisma.debt_paymentsOrderByWithRelationInput | Prisma.debt_paymentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.debt_paymentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` debt_payments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` debt_payments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned debt_payments
  **/
  _count?: true | Debt_paymentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Debt_paymentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Debt_paymentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Debt_paymentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Debt_paymentsMaxAggregateInputType
}

export type GetDebt_paymentsAggregateType<T extends Debt_paymentsAggregateArgs> = {
      [P in keyof T & keyof AggregateDebt_payments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDebt_payments[P]>
    : Prisma.GetScalarType<T[P], AggregateDebt_payments[P]>
}




export type debt_paymentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.debt_paymentsWhereInput
  orderBy?: Prisma.debt_paymentsOrderByWithAggregationInput | Prisma.debt_paymentsOrderByWithAggregationInput[]
  by: Prisma.Debt_paymentsScalarFieldEnum[] | Prisma.Debt_paymentsScalarFieldEnum
  having?: Prisma.debt_paymentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Debt_paymentsCountAggregateInputType | true
  _avg?: Debt_paymentsAvgAggregateInputType
  _sum?: Debt_paymentsSumAggregateInputType
  _min?: Debt_paymentsMinAggregateInputType
  _max?: Debt_paymentsMaxAggregateInputType
}

export type Debt_paymentsGroupByOutputType = {
  id: number
  debt_id: number | null
  payment_amount: runtime.Decimal
  payment_date: Date
  payment_method: string
  bank_account_id: number | null
  notes: string | null
  created_by: number | null
  created_at: Date | null
  _count: Debt_paymentsCountAggregateOutputType | null
  _avg: Debt_paymentsAvgAggregateOutputType | null
  _sum: Debt_paymentsSumAggregateOutputType | null
  _min: Debt_paymentsMinAggregateOutputType | null
  _max: Debt_paymentsMaxAggregateOutputType | null
}

type GetDebt_paymentsGroupByPayload<T extends debt_paymentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Debt_paymentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Debt_paymentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Debt_paymentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Debt_paymentsGroupByOutputType[P]>
      }
    >
  >



export type debt_paymentsWhereInput = {
  AND?: Prisma.debt_paymentsWhereInput | Prisma.debt_paymentsWhereInput[]
  OR?: Prisma.debt_paymentsWhereInput[]
  NOT?: Prisma.debt_paymentsWhereInput | Prisma.debt_paymentsWhereInput[]
  id?: Prisma.IntFilter<"debt_payments"> | number
  debt_id?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  payment_amount?: Prisma.DecimalFilter<"debt_payments"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFilter<"debt_payments"> | Date | string
  payment_method?: Prisma.StringFilter<"debt_payments"> | string
  bank_account_id?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  notes?: Prisma.StringNullableFilter<"debt_payments"> | string | null
  created_by?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"debt_payments"> | Date | string | null
  bank_accounts?: Prisma.XOR<Prisma.Bank_accountsNullableScalarRelationFilter, Prisma.bank_accountsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  debt_management?: Prisma.XOR<Prisma.Debt_managementNullableScalarRelationFilter, Prisma.debt_managementWhereInput> | null
}

export type debt_paymentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrderInput | Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  payment_date?: Prisma.SortOrder
  payment_method?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  bank_accounts?: Prisma.bank_accountsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
  debt_management?: Prisma.debt_managementOrderByWithRelationInput
}

export type debt_paymentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.debt_paymentsWhereInput | Prisma.debt_paymentsWhereInput[]
  OR?: Prisma.debt_paymentsWhereInput[]
  NOT?: Prisma.debt_paymentsWhereInput | Prisma.debt_paymentsWhereInput[]
  debt_id?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  payment_amount?: Prisma.DecimalFilter<"debt_payments"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFilter<"debt_payments"> | Date | string
  payment_method?: Prisma.StringFilter<"debt_payments"> | string
  bank_account_id?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  notes?: Prisma.StringNullableFilter<"debt_payments"> | string | null
  created_by?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"debt_payments"> | Date | string | null
  bank_accounts?: Prisma.XOR<Prisma.Bank_accountsNullableScalarRelationFilter, Prisma.bank_accountsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  debt_management?: Prisma.XOR<Prisma.Debt_managementNullableScalarRelationFilter, Prisma.debt_managementWhereInput> | null
}, "id">

export type debt_paymentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrderInput | Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  payment_date?: Prisma.SortOrder
  payment_method?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.debt_paymentsCountOrderByAggregateInput
  _avg?: Prisma.debt_paymentsAvgOrderByAggregateInput
  _max?: Prisma.debt_paymentsMaxOrderByAggregateInput
  _min?: Prisma.debt_paymentsMinOrderByAggregateInput
  _sum?: Prisma.debt_paymentsSumOrderByAggregateInput
}

export type debt_paymentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.debt_paymentsScalarWhereWithAggregatesInput | Prisma.debt_paymentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.debt_paymentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.debt_paymentsScalarWhereWithAggregatesInput | Prisma.debt_paymentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"debt_payments"> | number
  debt_id?: Prisma.IntNullableWithAggregatesFilter<"debt_payments"> | number | null
  payment_amount?: Prisma.DecimalWithAggregatesFilter<"debt_payments"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeWithAggregatesFilter<"debt_payments"> | Date | string
  payment_method?: Prisma.StringWithAggregatesFilter<"debt_payments"> | string
  bank_account_id?: Prisma.IntNullableWithAggregatesFilter<"debt_payments"> | number | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"debt_payments"> | string | null
  created_by?: Prisma.IntNullableWithAggregatesFilter<"debt_payments"> | number | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"debt_payments"> | Date | string | null
}

export type debt_paymentsCreateInput = {
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  notes?: string | null
  created_at?: Date | string | null
  bank_accounts?: Prisma.bank_accountsCreateNestedOneWithoutDebt_paymentsInput
  users?: Prisma.usersCreateNestedOneWithoutDebt_paymentsInput
  debt_management?: Prisma.debt_managementCreateNestedOneWithoutDebt_paymentsInput
}

export type debt_paymentsUncheckedCreateInput = {
  id?: number
  debt_id?: number | null
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  bank_account_id?: number | null
  notes?: string | null
  created_by?: number | null
  created_at?: Date | string | null
}

export type debt_paymentsUpdateInput = {
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bank_accounts?: Prisma.bank_accountsUpdateOneWithoutDebt_paymentsNestedInput
  users?: Prisma.usersUpdateOneWithoutDebt_paymentsNestedInput
  debt_management?: Prisma.debt_managementUpdateOneWithoutDebt_paymentsNestedInput
}

export type debt_paymentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  debt_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  bank_account_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsCreateManyInput = {
  id?: number
  debt_id?: number | null
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  bank_account_id?: number | null
  notes?: string | null
  created_by?: number | null
  created_at?: Date | string | null
}

export type debt_paymentsUpdateManyMutationInput = {
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  debt_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  bank_account_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Debt_paymentsListRelationFilter = {
  every?: Prisma.debt_paymentsWhereInput
  some?: Prisma.debt_paymentsWhereInput
  none?: Prisma.debt_paymentsWhereInput
}

export type debt_paymentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type debt_paymentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  payment_date?: Prisma.SortOrder
  payment_method?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type debt_paymentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
}

export type debt_paymentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  payment_date?: Prisma.SortOrder
  payment_method?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type debt_paymentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  payment_date?: Prisma.SortOrder
  payment_method?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type debt_paymentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  debt_id?: Prisma.SortOrder
  payment_amount?: Prisma.SortOrder
  bank_account_id?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
}

export type debt_paymentsCreateNestedManyWithoutBank_accountsInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput> | Prisma.debt_paymentsCreateWithoutBank_accountsInput[] | Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput | Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput[]
  createMany?: Prisma.debt_paymentsCreateManyBank_accountsInputEnvelope
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
}

export type debt_paymentsUncheckedCreateNestedManyWithoutBank_accountsInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput> | Prisma.debt_paymentsCreateWithoutBank_accountsInput[] | Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput | Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput[]
  createMany?: Prisma.debt_paymentsCreateManyBank_accountsInputEnvelope
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
}

export type debt_paymentsUpdateManyWithoutBank_accountsNestedInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput> | Prisma.debt_paymentsCreateWithoutBank_accountsInput[] | Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput | Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput[]
  upsert?: Prisma.debt_paymentsUpsertWithWhereUniqueWithoutBank_accountsInput | Prisma.debt_paymentsUpsertWithWhereUniqueWithoutBank_accountsInput[]
  createMany?: Prisma.debt_paymentsCreateManyBank_accountsInputEnvelope
  set?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  disconnect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  delete?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  update?: Prisma.debt_paymentsUpdateWithWhereUniqueWithoutBank_accountsInput | Prisma.debt_paymentsUpdateWithWhereUniqueWithoutBank_accountsInput[]
  updateMany?: Prisma.debt_paymentsUpdateManyWithWhereWithoutBank_accountsInput | Prisma.debt_paymentsUpdateManyWithWhereWithoutBank_accountsInput[]
  deleteMany?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
}

export type debt_paymentsUncheckedUpdateManyWithoutBank_accountsNestedInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput> | Prisma.debt_paymentsCreateWithoutBank_accountsInput[] | Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput | Prisma.debt_paymentsCreateOrConnectWithoutBank_accountsInput[]
  upsert?: Prisma.debt_paymentsUpsertWithWhereUniqueWithoutBank_accountsInput | Prisma.debt_paymentsUpsertWithWhereUniqueWithoutBank_accountsInput[]
  createMany?: Prisma.debt_paymentsCreateManyBank_accountsInputEnvelope
  set?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  disconnect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  delete?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  update?: Prisma.debt_paymentsUpdateWithWhereUniqueWithoutBank_accountsInput | Prisma.debt_paymentsUpdateWithWhereUniqueWithoutBank_accountsInput[]
  updateMany?: Prisma.debt_paymentsUpdateManyWithWhereWithoutBank_accountsInput | Prisma.debt_paymentsUpdateManyWithWhereWithoutBank_accountsInput[]
  deleteMany?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
}

export type debt_paymentsCreateNestedManyWithoutDebt_managementInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput> | Prisma.debt_paymentsCreateWithoutDebt_managementInput[] | Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput | Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput[]
  createMany?: Prisma.debt_paymentsCreateManyDebt_managementInputEnvelope
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
}

export type debt_paymentsUncheckedCreateNestedManyWithoutDebt_managementInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput> | Prisma.debt_paymentsCreateWithoutDebt_managementInput[] | Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput | Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput[]
  createMany?: Prisma.debt_paymentsCreateManyDebt_managementInputEnvelope
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
}

export type debt_paymentsUpdateManyWithoutDebt_managementNestedInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput> | Prisma.debt_paymentsCreateWithoutDebt_managementInput[] | Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput | Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput[]
  upsert?: Prisma.debt_paymentsUpsertWithWhereUniqueWithoutDebt_managementInput | Prisma.debt_paymentsUpsertWithWhereUniqueWithoutDebt_managementInput[]
  createMany?: Prisma.debt_paymentsCreateManyDebt_managementInputEnvelope
  set?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  disconnect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  delete?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  update?: Prisma.debt_paymentsUpdateWithWhereUniqueWithoutDebt_managementInput | Prisma.debt_paymentsUpdateWithWhereUniqueWithoutDebt_managementInput[]
  updateMany?: Prisma.debt_paymentsUpdateManyWithWhereWithoutDebt_managementInput | Prisma.debt_paymentsUpdateManyWithWhereWithoutDebt_managementInput[]
  deleteMany?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
}

export type debt_paymentsUncheckedUpdateManyWithoutDebt_managementNestedInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput> | Prisma.debt_paymentsCreateWithoutDebt_managementInput[] | Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput | Prisma.debt_paymentsCreateOrConnectWithoutDebt_managementInput[]
  upsert?: Prisma.debt_paymentsUpsertWithWhereUniqueWithoutDebt_managementInput | Prisma.debt_paymentsUpsertWithWhereUniqueWithoutDebt_managementInput[]
  createMany?: Prisma.debt_paymentsCreateManyDebt_managementInputEnvelope
  set?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  disconnect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  delete?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  update?: Prisma.debt_paymentsUpdateWithWhereUniqueWithoutDebt_managementInput | Prisma.debt_paymentsUpdateWithWhereUniqueWithoutDebt_managementInput[]
  updateMany?: Prisma.debt_paymentsUpdateManyWithWhereWithoutDebt_managementInput | Prisma.debt_paymentsUpdateManyWithWhereWithoutDebt_managementInput[]
  deleteMany?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
}

export type debt_paymentsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutUsersInput, Prisma.debt_paymentsUncheckedCreateWithoutUsersInput> | Prisma.debt_paymentsCreateWithoutUsersInput[] | Prisma.debt_paymentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutUsersInput | Prisma.debt_paymentsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.debt_paymentsCreateManyUsersInputEnvelope
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
}

export type debt_paymentsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutUsersInput, Prisma.debt_paymentsUncheckedCreateWithoutUsersInput> | Prisma.debt_paymentsCreateWithoutUsersInput[] | Prisma.debt_paymentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutUsersInput | Prisma.debt_paymentsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.debt_paymentsCreateManyUsersInputEnvelope
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
}

export type debt_paymentsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutUsersInput, Prisma.debt_paymentsUncheckedCreateWithoutUsersInput> | Prisma.debt_paymentsCreateWithoutUsersInput[] | Prisma.debt_paymentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutUsersInput | Prisma.debt_paymentsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.debt_paymentsUpsertWithWhereUniqueWithoutUsersInput | Prisma.debt_paymentsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.debt_paymentsCreateManyUsersInputEnvelope
  set?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  disconnect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  delete?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  update?: Prisma.debt_paymentsUpdateWithWhereUniqueWithoutUsersInput | Prisma.debt_paymentsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.debt_paymentsUpdateManyWithWhereWithoutUsersInput | Prisma.debt_paymentsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
}

export type debt_paymentsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.debt_paymentsCreateWithoutUsersInput, Prisma.debt_paymentsUncheckedCreateWithoutUsersInput> | Prisma.debt_paymentsCreateWithoutUsersInput[] | Prisma.debt_paymentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.debt_paymentsCreateOrConnectWithoutUsersInput | Prisma.debt_paymentsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.debt_paymentsUpsertWithWhereUniqueWithoutUsersInput | Prisma.debt_paymentsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.debt_paymentsCreateManyUsersInputEnvelope
  set?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  disconnect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  delete?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  connect?: Prisma.debt_paymentsWhereUniqueInput | Prisma.debt_paymentsWhereUniqueInput[]
  update?: Prisma.debt_paymentsUpdateWithWhereUniqueWithoutUsersInput | Prisma.debt_paymentsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.debt_paymentsUpdateManyWithWhereWithoutUsersInput | Prisma.debt_paymentsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
}

export type debt_paymentsCreateWithoutBank_accountsInput = {
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  notes?: string | null
  created_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutDebt_paymentsInput
  debt_management?: Prisma.debt_managementCreateNestedOneWithoutDebt_paymentsInput
}

export type debt_paymentsUncheckedCreateWithoutBank_accountsInput = {
  id?: number
  debt_id?: number | null
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  notes?: string | null
  created_by?: number | null
  created_at?: Date | string | null
}

export type debt_paymentsCreateOrConnectWithoutBank_accountsInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  create: Prisma.XOR<Prisma.debt_paymentsCreateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput>
}

export type debt_paymentsCreateManyBank_accountsInputEnvelope = {
  data: Prisma.debt_paymentsCreateManyBank_accountsInput | Prisma.debt_paymentsCreateManyBank_accountsInput[]
  skipDuplicates?: boolean
}

export type debt_paymentsUpsertWithWhereUniqueWithoutBank_accountsInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  update: Prisma.XOR<Prisma.debt_paymentsUpdateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedUpdateWithoutBank_accountsInput>
  create: Prisma.XOR<Prisma.debt_paymentsCreateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedCreateWithoutBank_accountsInput>
}

export type debt_paymentsUpdateWithWhereUniqueWithoutBank_accountsInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  data: Prisma.XOR<Prisma.debt_paymentsUpdateWithoutBank_accountsInput, Prisma.debt_paymentsUncheckedUpdateWithoutBank_accountsInput>
}

export type debt_paymentsUpdateManyWithWhereWithoutBank_accountsInput = {
  where: Prisma.debt_paymentsScalarWhereInput
  data: Prisma.XOR<Prisma.debt_paymentsUpdateManyMutationInput, Prisma.debt_paymentsUncheckedUpdateManyWithoutBank_accountsInput>
}

export type debt_paymentsScalarWhereInput = {
  AND?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
  OR?: Prisma.debt_paymentsScalarWhereInput[]
  NOT?: Prisma.debt_paymentsScalarWhereInput | Prisma.debt_paymentsScalarWhereInput[]
  id?: Prisma.IntFilter<"debt_payments"> | number
  debt_id?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  payment_amount?: Prisma.DecimalFilter<"debt_payments"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFilter<"debt_payments"> | Date | string
  payment_method?: Prisma.StringFilter<"debt_payments"> | string
  bank_account_id?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  notes?: Prisma.StringNullableFilter<"debt_payments"> | string | null
  created_by?: Prisma.IntNullableFilter<"debt_payments"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"debt_payments"> | Date | string | null
}

export type debt_paymentsCreateWithoutDebt_managementInput = {
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  notes?: string | null
  created_at?: Date | string | null
  bank_accounts?: Prisma.bank_accountsCreateNestedOneWithoutDebt_paymentsInput
  users?: Prisma.usersCreateNestedOneWithoutDebt_paymentsInput
}

export type debt_paymentsUncheckedCreateWithoutDebt_managementInput = {
  id?: number
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  bank_account_id?: number | null
  notes?: string | null
  created_by?: number | null
  created_at?: Date | string | null
}

export type debt_paymentsCreateOrConnectWithoutDebt_managementInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  create: Prisma.XOR<Prisma.debt_paymentsCreateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput>
}

export type debt_paymentsCreateManyDebt_managementInputEnvelope = {
  data: Prisma.debt_paymentsCreateManyDebt_managementInput | Prisma.debt_paymentsCreateManyDebt_managementInput[]
  skipDuplicates?: boolean
}

export type debt_paymentsUpsertWithWhereUniqueWithoutDebt_managementInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  update: Prisma.XOR<Prisma.debt_paymentsUpdateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedUpdateWithoutDebt_managementInput>
  create: Prisma.XOR<Prisma.debt_paymentsCreateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedCreateWithoutDebt_managementInput>
}

export type debt_paymentsUpdateWithWhereUniqueWithoutDebt_managementInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  data: Prisma.XOR<Prisma.debt_paymentsUpdateWithoutDebt_managementInput, Prisma.debt_paymentsUncheckedUpdateWithoutDebt_managementInput>
}

export type debt_paymentsUpdateManyWithWhereWithoutDebt_managementInput = {
  where: Prisma.debt_paymentsScalarWhereInput
  data: Prisma.XOR<Prisma.debt_paymentsUpdateManyMutationInput, Prisma.debt_paymentsUncheckedUpdateManyWithoutDebt_managementInput>
}

export type debt_paymentsCreateWithoutUsersInput = {
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  notes?: string | null
  created_at?: Date | string | null
  bank_accounts?: Prisma.bank_accountsCreateNestedOneWithoutDebt_paymentsInput
  debt_management?: Prisma.debt_managementCreateNestedOneWithoutDebt_paymentsInput
}

export type debt_paymentsUncheckedCreateWithoutUsersInput = {
  id?: number
  debt_id?: number | null
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  bank_account_id?: number | null
  notes?: string | null
  created_at?: Date | string | null
}

export type debt_paymentsCreateOrConnectWithoutUsersInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  create: Prisma.XOR<Prisma.debt_paymentsCreateWithoutUsersInput, Prisma.debt_paymentsUncheckedCreateWithoutUsersInput>
}

export type debt_paymentsCreateManyUsersInputEnvelope = {
  data: Prisma.debt_paymentsCreateManyUsersInput | Prisma.debt_paymentsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type debt_paymentsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  update: Prisma.XOR<Prisma.debt_paymentsUpdateWithoutUsersInput, Prisma.debt_paymentsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.debt_paymentsCreateWithoutUsersInput, Prisma.debt_paymentsUncheckedCreateWithoutUsersInput>
}

export type debt_paymentsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.debt_paymentsWhereUniqueInput
  data: Prisma.XOR<Prisma.debt_paymentsUpdateWithoutUsersInput, Prisma.debt_paymentsUncheckedUpdateWithoutUsersInput>
}

export type debt_paymentsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.debt_paymentsScalarWhereInput
  data: Prisma.XOR<Prisma.debt_paymentsUpdateManyMutationInput, Prisma.debt_paymentsUncheckedUpdateManyWithoutUsersInput>
}

export type debt_paymentsCreateManyBank_accountsInput = {
  id?: number
  debt_id?: number | null
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  notes?: string | null
  created_by?: number | null
  created_at?: Date | string | null
}

export type debt_paymentsUpdateWithoutBank_accountsInput = {
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutDebt_paymentsNestedInput
  debt_management?: Prisma.debt_managementUpdateOneWithoutDebt_paymentsNestedInput
}

export type debt_paymentsUncheckedUpdateWithoutBank_accountsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  debt_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsUncheckedUpdateManyWithoutBank_accountsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  debt_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsCreateManyDebt_managementInput = {
  id?: number
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  bank_account_id?: number | null
  notes?: string | null
  created_by?: number | null
  created_at?: Date | string | null
}

export type debt_paymentsUpdateWithoutDebt_managementInput = {
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bank_accounts?: Prisma.bank_accountsUpdateOneWithoutDebt_paymentsNestedInput
  users?: Prisma.usersUpdateOneWithoutDebt_paymentsNestedInput
}

export type debt_paymentsUncheckedUpdateWithoutDebt_managementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  bank_account_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsUncheckedUpdateManyWithoutDebt_managementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  bank_account_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsCreateManyUsersInput = {
  id?: number
  debt_id?: number | null
  payment_amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date: Date | string
  payment_method: string
  bank_account_id?: number | null
  notes?: string | null
  created_at?: Date | string | null
}

export type debt_paymentsUpdateWithoutUsersInput = {
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bank_accounts?: Prisma.bank_accountsUpdateOneWithoutDebt_paymentsNestedInput
  debt_management?: Prisma.debt_managementUpdateOneWithoutDebt_paymentsNestedInput
}

export type debt_paymentsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  debt_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  bank_account_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type debt_paymentsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  debt_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  payment_amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  payment_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.StringFieldUpdateOperationsInput | string
  bank_account_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type debt_paymentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  debt_id?: boolean
  payment_amount?: boolean
  payment_date?: boolean
  payment_method?: boolean
  bank_account_id?: boolean
  notes?: boolean
  created_by?: boolean
  created_at?: boolean
  bank_accounts?: boolean | Prisma.debt_payments$bank_accountsArgs<ExtArgs>
  users?: boolean | Prisma.debt_payments$usersArgs<ExtArgs>
  debt_management?: boolean | Prisma.debt_payments$debt_managementArgs<ExtArgs>
}, ExtArgs["result"]["debt_payments"]>

export type debt_paymentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  debt_id?: boolean
  payment_amount?: boolean
  payment_date?: boolean
  payment_method?: boolean
  bank_account_id?: boolean
  notes?: boolean
  created_by?: boolean
  created_at?: boolean
  bank_accounts?: boolean | Prisma.debt_payments$bank_accountsArgs<ExtArgs>
  users?: boolean | Prisma.debt_payments$usersArgs<ExtArgs>
  debt_management?: boolean | Prisma.debt_payments$debt_managementArgs<ExtArgs>
}, ExtArgs["result"]["debt_payments"]>

export type debt_paymentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  debt_id?: boolean
  payment_amount?: boolean
  payment_date?: boolean
  payment_method?: boolean
  bank_account_id?: boolean
  notes?: boolean
  created_by?: boolean
  created_at?: boolean
  bank_accounts?: boolean | Prisma.debt_payments$bank_accountsArgs<ExtArgs>
  users?: boolean | Prisma.debt_payments$usersArgs<ExtArgs>
  debt_management?: boolean | Prisma.debt_payments$debt_managementArgs<ExtArgs>
}, ExtArgs["result"]["debt_payments"]>

export type debt_paymentsSelectScalar = {
  id?: boolean
  debt_id?: boolean
  payment_amount?: boolean
  payment_date?: boolean
  payment_method?: boolean
  bank_account_id?: boolean
  notes?: boolean
  created_by?: boolean
  created_at?: boolean
}

export type debt_paymentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "debt_id" | "payment_amount" | "payment_date" | "payment_method" | "bank_account_id" | "notes" | "created_by" | "created_at", ExtArgs["result"]["debt_payments"]>
export type debt_paymentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bank_accounts?: boolean | Prisma.debt_payments$bank_accountsArgs<ExtArgs>
  users?: boolean | Prisma.debt_payments$usersArgs<ExtArgs>
  debt_management?: boolean | Prisma.debt_payments$debt_managementArgs<ExtArgs>
}
export type debt_paymentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bank_accounts?: boolean | Prisma.debt_payments$bank_accountsArgs<ExtArgs>
  users?: boolean | Prisma.debt_payments$usersArgs<ExtArgs>
  debt_management?: boolean | Prisma.debt_payments$debt_managementArgs<ExtArgs>
}
export type debt_paymentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bank_accounts?: boolean | Prisma.debt_payments$bank_accountsArgs<ExtArgs>
  users?: boolean | Prisma.debt_payments$usersArgs<ExtArgs>
  debt_management?: boolean | Prisma.debt_payments$debt_managementArgs<ExtArgs>
}

export type $debt_paymentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "debt_payments"
  objects: {
    bank_accounts: Prisma.$bank_accountsPayload<ExtArgs> | null
    users: Prisma.$usersPayload<ExtArgs> | null
    debt_management: Prisma.$debt_managementPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    debt_id: number | null
    payment_amount: runtime.Decimal
    payment_date: Date
    payment_method: string
    bank_account_id: number | null
    notes: string | null
    created_by: number | null
    created_at: Date | null
  }, ExtArgs["result"]["debt_payments"]>
  composites: {}
}

export type debt_paymentsGetPayload<S extends boolean | null | undefined | debt_paymentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload, S>

export type debt_paymentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<debt_paymentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Debt_paymentsCountAggregateInputType | true
  }

export interface debt_paymentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['debt_payments'], meta: { name: 'debt_payments' } }
  /**
   * Find zero or one Debt_payments that matches the filter.
   * @param {debt_paymentsFindUniqueArgs} args - Arguments to find a Debt_payments
   * @example
   * // Get one Debt_payments
   * const debt_payments = await prisma.debt_payments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends debt_paymentsFindUniqueArgs>(args: Prisma.SelectSubset<T, debt_paymentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Debt_payments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {debt_paymentsFindUniqueOrThrowArgs} args - Arguments to find a Debt_payments
   * @example
   * // Get one Debt_payments
   * const debt_payments = await prisma.debt_payments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends debt_paymentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, debt_paymentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Debt_payments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {debt_paymentsFindFirstArgs} args - Arguments to find a Debt_payments
   * @example
   * // Get one Debt_payments
   * const debt_payments = await prisma.debt_payments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends debt_paymentsFindFirstArgs>(args?: Prisma.SelectSubset<T, debt_paymentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Debt_payments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {debt_paymentsFindFirstOrThrowArgs} args - Arguments to find a Debt_payments
   * @example
   * // Get one Debt_payments
   * const debt_payments = await prisma.debt_payments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends debt_paymentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, debt_paymentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Debt_payments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {debt_paymentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Debt_payments
   * const debt_payments = await prisma.debt_payments.findMany()
   * 
   * // Get first 10 Debt_payments
   * const debt_payments = await prisma.debt_payments.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const debt_paymentsWithIdOnly = await prisma.debt_payments.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends debt_paymentsFindManyArgs>(args?: Prisma.SelectSubset<T, debt_paymentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Debt_payments.
   * @param {debt_paymentsCreateArgs} args - Arguments to create a Debt_payments.
   * @example
   * // Create one Debt_payments
   * const Debt_payments = await prisma.debt_payments.create({
   *   data: {
   *     // ... data to create a Debt_payments
   *   }
   * })
   * 
   */
  create<T extends debt_paymentsCreateArgs>(args: Prisma.SelectSubset<T, debt_paymentsCreateArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Debt_payments.
   * @param {debt_paymentsCreateManyArgs} args - Arguments to create many Debt_payments.
   * @example
   * // Create many Debt_payments
   * const debt_payments = await prisma.debt_payments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends debt_paymentsCreateManyArgs>(args?: Prisma.SelectSubset<T, debt_paymentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Debt_payments and returns the data saved in the database.
   * @param {debt_paymentsCreateManyAndReturnArgs} args - Arguments to create many Debt_payments.
   * @example
   * // Create many Debt_payments
   * const debt_payments = await prisma.debt_payments.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Debt_payments and only return the `id`
   * const debt_paymentsWithIdOnly = await prisma.debt_payments.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends debt_paymentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, debt_paymentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Debt_payments.
   * @param {debt_paymentsDeleteArgs} args - Arguments to delete one Debt_payments.
   * @example
   * // Delete one Debt_payments
   * const Debt_payments = await prisma.debt_payments.delete({
   *   where: {
   *     // ... filter to delete one Debt_payments
   *   }
   * })
   * 
   */
  delete<T extends debt_paymentsDeleteArgs>(args: Prisma.SelectSubset<T, debt_paymentsDeleteArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Debt_payments.
   * @param {debt_paymentsUpdateArgs} args - Arguments to update one Debt_payments.
   * @example
   * // Update one Debt_payments
   * const debt_payments = await prisma.debt_payments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends debt_paymentsUpdateArgs>(args: Prisma.SelectSubset<T, debt_paymentsUpdateArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Debt_payments.
   * @param {debt_paymentsDeleteManyArgs} args - Arguments to filter Debt_payments to delete.
   * @example
   * // Delete a few Debt_payments
   * const { count } = await prisma.debt_payments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends debt_paymentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, debt_paymentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Debt_payments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {debt_paymentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Debt_payments
   * const debt_payments = await prisma.debt_payments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends debt_paymentsUpdateManyArgs>(args: Prisma.SelectSubset<T, debt_paymentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Debt_payments and returns the data updated in the database.
   * @param {debt_paymentsUpdateManyAndReturnArgs} args - Arguments to update many Debt_payments.
   * @example
   * // Update many Debt_payments
   * const debt_payments = await prisma.debt_payments.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Debt_payments and only return the `id`
   * const debt_paymentsWithIdOnly = await prisma.debt_payments.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends debt_paymentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, debt_paymentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Debt_payments.
   * @param {debt_paymentsUpsertArgs} args - Arguments to update or create a Debt_payments.
   * @example
   * // Update or create a Debt_payments
   * const debt_payments = await prisma.debt_payments.upsert({
   *   create: {
   *     // ... data to create a Debt_payments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Debt_payments we want to update
   *   }
   * })
   */
  upsert<T extends debt_paymentsUpsertArgs>(args: Prisma.SelectSubset<T, debt_paymentsUpsertArgs<ExtArgs>>): Prisma.Prisma__debt_paymentsClient<runtime.Types.Result.GetResult<Prisma.$debt_paymentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Debt_payments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {debt_paymentsCountArgs} args - Arguments to filter Debt_payments to count.
   * @example
   * // Count the number of Debt_payments
   * const count = await prisma.debt_payments.count({
   *   where: {
   *     // ... the filter for the Debt_payments we want to count
   *   }
   * })
  **/
  count<T extends debt_paymentsCountArgs>(
    args?: Prisma.Subset<T, debt_paymentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Debt_paymentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Debt_payments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Debt_paymentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Debt_paymentsAggregateArgs>(args: Prisma.Subset<T, Debt_paymentsAggregateArgs>): Prisma.PrismaPromise<GetDebt_paymentsAggregateType<T>>

  /**
   * Group by Debt_payments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {debt_paymentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends debt_paymentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: debt_paymentsGroupByArgs['orderBy'] }
      : { orderBy?: debt_paymentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, debt_paymentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDebt_paymentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the debt_payments model
 */
readonly fields: debt_paymentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for debt_payments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__debt_paymentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bank_accounts<T extends Prisma.debt_payments$bank_accountsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.debt_payments$bank_accountsArgs<ExtArgs>>): Prisma.Prisma__bank_accountsClient<runtime.Types.Result.GetResult<Prisma.$bank_accountsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.debt_payments$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.debt_payments$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  debt_management<T extends Prisma.debt_payments$debt_managementArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.debt_payments$debt_managementArgs<ExtArgs>>): Prisma.Prisma__debt_managementClient<runtime.Types.Result.GetResult<Prisma.$debt_managementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the debt_payments model
 */
export interface debt_paymentsFieldRefs {
  readonly id: Prisma.FieldRef<"debt_payments", 'Int'>
  readonly debt_id: Prisma.FieldRef<"debt_payments", 'Int'>
  readonly payment_amount: Prisma.FieldRef<"debt_payments", 'Decimal'>
  readonly payment_date: Prisma.FieldRef<"debt_payments", 'DateTime'>
  readonly payment_method: Prisma.FieldRef<"debt_payments", 'String'>
  readonly bank_account_id: Prisma.FieldRef<"debt_payments", 'Int'>
  readonly notes: Prisma.FieldRef<"debt_payments", 'String'>
  readonly created_by: Prisma.FieldRef<"debt_payments", 'Int'>
  readonly created_at: Prisma.FieldRef<"debt_payments", 'DateTime'>
}
    

// Custom InputTypes
/**
 * debt_payments findUnique
 */
export type debt_paymentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * Filter, which debt_payments to fetch.
   */
  where: Prisma.debt_paymentsWhereUniqueInput
}

/**
 * debt_payments findUniqueOrThrow
 */
export type debt_paymentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * Filter, which debt_payments to fetch.
   */
  where: Prisma.debt_paymentsWhereUniqueInput
}

/**
 * debt_payments findFirst
 */
export type debt_paymentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * Filter, which debt_payments to fetch.
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of debt_payments to fetch.
   */
  orderBy?: Prisma.debt_paymentsOrderByWithRelationInput | Prisma.debt_paymentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for debt_payments.
   */
  cursor?: Prisma.debt_paymentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` debt_payments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` debt_payments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of debt_payments.
   */
  distinct?: Prisma.Debt_paymentsScalarFieldEnum | Prisma.Debt_paymentsScalarFieldEnum[]
}

/**
 * debt_payments findFirstOrThrow
 */
export type debt_paymentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * Filter, which debt_payments to fetch.
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of debt_payments to fetch.
   */
  orderBy?: Prisma.debt_paymentsOrderByWithRelationInput | Prisma.debt_paymentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for debt_payments.
   */
  cursor?: Prisma.debt_paymentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` debt_payments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` debt_payments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of debt_payments.
   */
  distinct?: Prisma.Debt_paymentsScalarFieldEnum | Prisma.Debt_paymentsScalarFieldEnum[]
}

/**
 * debt_payments findMany
 */
export type debt_paymentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * Filter, which debt_payments to fetch.
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of debt_payments to fetch.
   */
  orderBy?: Prisma.debt_paymentsOrderByWithRelationInput | Prisma.debt_paymentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing debt_payments.
   */
  cursor?: Prisma.debt_paymentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` debt_payments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` debt_payments.
   */
  skip?: number
  distinct?: Prisma.Debt_paymentsScalarFieldEnum | Prisma.Debt_paymentsScalarFieldEnum[]
}

/**
 * debt_payments create
 */
export type debt_paymentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * The data needed to create a debt_payments.
   */
  data: Prisma.XOR<Prisma.debt_paymentsCreateInput, Prisma.debt_paymentsUncheckedCreateInput>
}

/**
 * debt_payments createMany
 */
export type debt_paymentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many debt_payments.
   */
  data: Prisma.debt_paymentsCreateManyInput | Prisma.debt_paymentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * debt_payments createManyAndReturn
 */
export type debt_paymentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * The data used to create many debt_payments.
   */
  data: Prisma.debt_paymentsCreateManyInput | Prisma.debt_paymentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * debt_payments update
 */
export type debt_paymentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * The data needed to update a debt_payments.
   */
  data: Prisma.XOR<Prisma.debt_paymentsUpdateInput, Prisma.debt_paymentsUncheckedUpdateInput>
  /**
   * Choose, which debt_payments to update.
   */
  where: Prisma.debt_paymentsWhereUniqueInput
}

/**
 * debt_payments updateMany
 */
export type debt_paymentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update debt_payments.
   */
  data: Prisma.XOR<Prisma.debt_paymentsUpdateManyMutationInput, Prisma.debt_paymentsUncheckedUpdateManyInput>
  /**
   * Filter which debt_payments to update
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * Limit how many debt_payments to update.
   */
  limit?: number
}

/**
 * debt_payments updateManyAndReturn
 */
export type debt_paymentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * The data used to update debt_payments.
   */
  data: Prisma.XOR<Prisma.debt_paymentsUpdateManyMutationInput, Prisma.debt_paymentsUncheckedUpdateManyInput>
  /**
   * Filter which debt_payments to update
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * Limit how many debt_payments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * debt_payments upsert
 */
export type debt_paymentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * The filter to search for the debt_payments to update in case it exists.
   */
  where: Prisma.debt_paymentsWhereUniqueInput
  /**
   * In case the debt_payments found by the `where` argument doesn't exist, create a new debt_payments with this data.
   */
  create: Prisma.XOR<Prisma.debt_paymentsCreateInput, Prisma.debt_paymentsUncheckedCreateInput>
  /**
   * In case the debt_payments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.debt_paymentsUpdateInput, Prisma.debt_paymentsUncheckedUpdateInput>
}

/**
 * debt_payments delete
 */
export type debt_paymentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
  /**
   * Filter which debt_payments to delete.
   */
  where: Prisma.debt_paymentsWhereUniqueInput
}

/**
 * debt_payments deleteMany
 */
export type debt_paymentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which debt_payments to delete
   */
  where?: Prisma.debt_paymentsWhereInput
  /**
   * Limit how many debt_payments to delete.
   */
  limit?: number
}

/**
 * debt_payments.bank_accounts
 */
export type debt_payments$bank_accountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bank_accounts
   */
  select?: Prisma.bank_accountsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bank_accounts
   */
  omit?: Prisma.bank_accountsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bank_accountsInclude<ExtArgs> | null
  where?: Prisma.bank_accountsWhereInput
}

/**
 * debt_payments.users
 */
export type debt_payments$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * debt_payments.debt_management
 */
export type debt_payments$debt_managementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_management
   */
  select?: Prisma.debt_managementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_management
   */
  omit?: Prisma.debt_managementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_managementInclude<ExtArgs> | null
  where?: Prisma.debt_managementWhereInput
}

/**
 * debt_payments without action
 */
export type debt_paymentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the debt_payments
   */
  select?: Prisma.debt_paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the debt_payments
   */
  omit?: Prisma.debt_paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.debt_paymentsInclude<ExtArgs> | null
}
