
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `inventory_transaction_details` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model inventory_transaction_details
 * 
 */
export type inventory_transaction_detailsModel = runtime.Types.Result.DefaultSelection<Prisma.$inventory_transaction_detailsPayload>

export type AggregateInventory_transaction_details = {
  _count: Inventory_transaction_detailsCountAggregateOutputType | null
  _avg: Inventory_transaction_detailsAvgAggregateOutputType | null
  _sum: Inventory_transaction_detailsSumAggregateOutputType | null
  _min: Inventory_transaction_detailsMinAggregateOutputType | null
  _max: Inventory_transaction_detailsMaxAggregateOutputType | null
}

export type Inventory_transaction_detailsAvgAggregateOutputType = {
  id: number | null
  transaction_id: number | null
  product_id: number | null
  material_id: number | null
  quantity: runtime.Decimal | null
  unit_price: runtime.Decimal | null
  total_amount: runtime.Decimal | null
}

export type Inventory_transaction_detailsSumAggregateOutputType = {
  id: number | null
  transaction_id: number | null
  product_id: number | null
  material_id: number | null
  quantity: runtime.Decimal | null
  unit_price: runtime.Decimal | null
  total_amount: runtime.Decimal | null
}

export type Inventory_transaction_detailsMinAggregateOutputType = {
  id: number | null
  transaction_id: number | null
  product_id: number | null
  material_id: number | null
  quantity: runtime.Decimal | null
  unit_price: runtime.Decimal | null
  total_amount: runtime.Decimal | null
  notes: string | null
}

export type Inventory_transaction_detailsMaxAggregateOutputType = {
  id: number | null
  transaction_id: number | null
  product_id: number | null
  material_id: number | null
  quantity: runtime.Decimal | null
  unit_price: runtime.Decimal | null
  total_amount: runtime.Decimal | null
  notes: string | null
}

export type Inventory_transaction_detailsCountAggregateOutputType = {
  id: number
  transaction_id: number
  product_id: number
  material_id: number
  quantity: number
  unit_price: number
  total_amount: number
  notes: number
  _all: number
}


export type Inventory_transaction_detailsAvgAggregateInputType = {
  id?: true
  transaction_id?: true
  product_id?: true
  material_id?: true
  quantity?: true
  unit_price?: true
  total_amount?: true
}

export type Inventory_transaction_detailsSumAggregateInputType = {
  id?: true
  transaction_id?: true
  product_id?: true
  material_id?: true
  quantity?: true
  unit_price?: true
  total_amount?: true
}

export type Inventory_transaction_detailsMinAggregateInputType = {
  id?: true
  transaction_id?: true
  product_id?: true
  material_id?: true
  quantity?: true
  unit_price?: true
  total_amount?: true
  notes?: true
}

export type Inventory_transaction_detailsMaxAggregateInputType = {
  id?: true
  transaction_id?: true
  product_id?: true
  material_id?: true
  quantity?: true
  unit_price?: true
  total_amount?: true
  notes?: true
}

export type Inventory_transaction_detailsCountAggregateInputType = {
  id?: true
  transaction_id?: true
  product_id?: true
  material_id?: true
  quantity?: true
  unit_price?: true
  total_amount?: true
  notes?: true
  _all?: true
}

export type Inventory_transaction_detailsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which inventory_transaction_details to aggregate.
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inventory_transaction_details to fetch.
   */
  orderBy?: Prisma.inventory_transaction_detailsOrderByWithRelationInput | Prisma.inventory_transaction_detailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.inventory_transaction_detailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inventory_transaction_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inventory_transaction_details.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned inventory_transaction_details
  **/
  _count?: true | Inventory_transaction_detailsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Inventory_transaction_detailsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Inventory_transaction_detailsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Inventory_transaction_detailsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Inventory_transaction_detailsMaxAggregateInputType
}

export type GetInventory_transaction_detailsAggregateType<T extends Inventory_transaction_detailsAggregateArgs> = {
      [P in keyof T & keyof AggregateInventory_transaction_details]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInventory_transaction_details[P]>
    : Prisma.GetScalarType<T[P], AggregateInventory_transaction_details[P]>
}




export type inventory_transaction_detailsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.inventory_transaction_detailsWhereInput
  orderBy?: Prisma.inventory_transaction_detailsOrderByWithAggregationInput | Prisma.inventory_transaction_detailsOrderByWithAggregationInput[]
  by: Prisma.Inventory_transaction_detailsScalarFieldEnum[] | Prisma.Inventory_transaction_detailsScalarFieldEnum
  having?: Prisma.inventory_transaction_detailsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Inventory_transaction_detailsCountAggregateInputType | true
  _avg?: Inventory_transaction_detailsAvgAggregateInputType
  _sum?: Inventory_transaction_detailsSumAggregateInputType
  _min?: Inventory_transaction_detailsMinAggregateInputType
  _max?: Inventory_transaction_detailsMaxAggregateInputType
}

export type Inventory_transaction_detailsGroupByOutputType = {
  id: number
  transaction_id: number | null
  product_id: number | null
  material_id: number | null
  quantity: runtime.Decimal
  unit_price: runtime.Decimal | null
  total_amount: runtime.Decimal | null
  notes: string | null
  _count: Inventory_transaction_detailsCountAggregateOutputType | null
  _avg: Inventory_transaction_detailsAvgAggregateOutputType | null
  _sum: Inventory_transaction_detailsSumAggregateOutputType | null
  _min: Inventory_transaction_detailsMinAggregateOutputType | null
  _max: Inventory_transaction_detailsMaxAggregateOutputType | null
}

type GetInventory_transaction_detailsGroupByPayload<T extends inventory_transaction_detailsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Inventory_transaction_detailsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Inventory_transaction_detailsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Inventory_transaction_detailsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Inventory_transaction_detailsGroupByOutputType[P]>
      }
    >
  >



export type inventory_transaction_detailsWhereInput = {
  AND?: Prisma.inventory_transaction_detailsWhereInput | Prisma.inventory_transaction_detailsWhereInput[]
  OR?: Prisma.inventory_transaction_detailsWhereInput[]
  NOT?: Prisma.inventory_transaction_detailsWhereInput | Prisma.inventory_transaction_detailsWhereInput[]
  id?: Prisma.IntFilter<"inventory_transaction_details"> | number
  transaction_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  product_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  material_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  quantity?: Prisma.DecimalFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.DecimalNullableFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.DecimalNullableFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableFilter<"inventory_transaction_details"> | string | null
  materials?: Prisma.XOR<Prisma.MaterialsNullableScalarRelationFilter, Prisma.materialsWhereInput> | null
  products?: Prisma.XOR<Prisma.ProductsNullableScalarRelationFilter, Prisma.productsWhereInput> | null
  inventory_transactions?: Prisma.XOR<Prisma.Inventory_transactionsNullableScalarRelationFilter, Prisma.inventory_transactionsWhereInput> | null
}

export type inventory_transaction_detailsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrderInput | Prisma.SortOrder
  product_id?: Prisma.SortOrderInput | Prisma.SortOrder
  material_id?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrderInput | Prisma.SortOrder
  total_amount?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  materials?: Prisma.materialsOrderByWithRelationInput
  products?: Prisma.productsOrderByWithRelationInput
  inventory_transactions?: Prisma.inventory_transactionsOrderByWithRelationInput
}

export type inventory_transaction_detailsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.inventory_transaction_detailsWhereInput | Prisma.inventory_transaction_detailsWhereInput[]
  OR?: Prisma.inventory_transaction_detailsWhereInput[]
  NOT?: Prisma.inventory_transaction_detailsWhereInput | Prisma.inventory_transaction_detailsWhereInput[]
  transaction_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  product_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  material_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  quantity?: Prisma.DecimalFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.DecimalNullableFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.DecimalNullableFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableFilter<"inventory_transaction_details"> | string | null
  materials?: Prisma.XOR<Prisma.MaterialsNullableScalarRelationFilter, Prisma.materialsWhereInput> | null
  products?: Prisma.XOR<Prisma.ProductsNullableScalarRelationFilter, Prisma.productsWhereInput> | null
  inventory_transactions?: Prisma.XOR<Prisma.Inventory_transactionsNullableScalarRelationFilter, Prisma.inventory_transactionsWhereInput> | null
}, "id">

export type inventory_transaction_detailsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrderInput | Prisma.SortOrder
  product_id?: Prisma.SortOrderInput | Prisma.SortOrder
  material_id?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrderInput | Prisma.SortOrder
  total_amount?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.inventory_transaction_detailsCountOrderByAggregateInput
  _avg?: Prisma.inventory_transaction_detailsAvgOrderByAggregateInput
  _max?: Prisma.inventory_transaction_detailsMaxOrderByAggregateInput
  _min?: Prisma.inventory_transaction_detailsMinOrderByAggregateInput
  _sum?: Prisma.inventory_transaction_detailsSumOrderByAggregateInput
}

export type inventory_transaction_detailsScalarWhereWithAggregatesInput = {
  AND?: Prisma.inventory_transaction_detailsScalarWhereWithAggregatesInput | Prisma.inventory_transaction_detailsScalarWhereWithAggregatesInput[]
  OR?: Prisma.inventory_transaction_detailsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.inventory_transaction_detailsScalarWhereWithAggregatesInput | Prisma.inventory_transaction_detailsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"inventory_transaction_details"> | number
  transaction_id?: Prisma.IntNullableWithAggregatesFilter<"inventory_transaction_details"> | number | null
  product_id?: Prisma.IntNullableWithAggregatesFilter<"inventory_transaction_details"> | number | null
  material_id?: Prisma.IntNullableWithAggregatesFilter<"inventory_transaction_details"> | number | null
  quantity?: Prisma.DecimalWithAggregatesFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.DecimalNullableWithAggregatesFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.DecimalNullableWithAggregatesFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"inventory_transaction_details"> | string | null
}

export type inventory_transaction_detailsCreateInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  materials?: Prisma.materialsCreateNestedOneWithoutInventory_transaction_detailsInput
  products?: Prisma.productsCreateNestedOneWithoutInventory_transaction_detailsInput
  inventory_transactions?: Prisma.inventory_transactionsCreateNestedOneWithoutInventory_transaction_detailsInput
}

export type inventory_transaction_detailsUncheckedCreateInput = {
  id?: number
  transaction_id?: number | null
  product_id?: number | null
  material_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsUpdateInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  materials?: Prisma.materialsUpdateOneWithoutInventory_transaction_detailsNestedInput
  products?: Prisma.productsUpdateOneWithoutInventory_transaction_detailsNestedInput
  inventory_transactions?: Prisma.inventory_transactionsUpdateOneWithoutInventory_transaction_detailsNestedInput
}

export type inventory_transaction_detailsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  transaction_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  product_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  material_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsCreateManyInput = {
  id?: number
  transaction_id?: number | null
  product_id?: number | null
  material_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsUpdateManyMutationInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  transaction_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  product_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  material_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  material_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrder
  total_amount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type inventory_transaction_detailsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  material_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrder
  total_amount?: Prisma.SortOrder
}

export type inventory_transaction_detailsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  material_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrder
  total_amount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type inventory_transaction_detailsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  material_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrder
  total_amount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type inventory_transaction_detailsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transaction_id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  material_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit_price?: Prisma.SortOrder
  total_amount?: Prisma.SortOrder
}

export type Inventory_transaction_detailsListRelationFilter = {
  every?: Prisma.inventory_transaction_detailsWhereInput
  some?: Prisma.inventory_transaction_detailsWhereInput
  none?: Prisma.inventory_transaction_detailsWhereInput
}

export type inventory_transaction_detailsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type inventory_transaction_detailsCreateNestedManyWithoutInventory_transactionsInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput> | Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyInventory_transactionsInputEnvelope
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
}

export type inventory_transaction_detailsUncheckedCreateNestedManyWithoutInventory_transactionsInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput> | Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyInventory_transactionsInputEnvelope
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
}

export type inventory_transaction_detailsUpdateManyWithoutInventory_transactionsNestedInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput> | Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput[]
  upsert?: Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutInventory_transactionsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyInventory_transactionsInputEnvelope
  set?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  disconnect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  delete?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  update?: Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutInventory_transactionsInput[]
  updateMany?: Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutInventory_transactionsInput[]
  deleteMany?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
}

export type inventory_transaction_detailsUncheckedUpdateManyWithoutInventory_transactionsNestedInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput> | Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput[]
  upsert?: Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutInventory_transactionsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyInventory_transactionsInputEnvelope
  set?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  disconnect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  delete?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  update?: Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutInventory_transactionsInput[]
  updateMany?: Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutInventory_transactionsInput | Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutInventory_transactionsInput[]
  deleteMany?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
}

export type inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput> | Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyMaterialsInputEnvelope
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
}

export type inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput> | Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyMaterialsInputEnvelope
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
}

export type inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput> | Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput[]
  upsert?: Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutMaterialsInput | Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutMaterialsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyMaterialsInputEnvelope
  set?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  disconnect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  delete?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  update?: Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutMaterialsInput | Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutMaterialsInput[]
  updateMany?: Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutMaterialsInput | Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutMaterialsInput[]
  deleteMany?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
}

export type inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput> | Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput[]
  upsert?: Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutMaterialsInput | Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutMaterialsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyMaterialsInputEnvelope
  set?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  disconnect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  delete?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  update?: Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutMaterialsInput | Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutMaterialsInput[]
  updateMany?: Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutMaterialsInput | Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutMaterialsInput[]
  deleteMany?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
}

export type inventory_transaction_detailsCreateNestedManyWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput> | Prisma.inventory_transaction_detailsCreateWithoutProductsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyProductsInputEnvelope
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
}

export type inventory_transaction_detailsUncheckedCreateNestedManyWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput> | Prisma.inventory_transaction_detailsCreateWithoutProductsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyProductsInputEnvelope
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
}

export type inventory_transaction_detailsUpdateManyWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput> | Prisma.inventory_transaction_detailsCreateWithoutProductsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput[]
  upsert?: Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutProductsInput | Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutProductsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyProductsInputEnvelope
  set?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  disconnect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  delete?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  update?: Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutProductsInput | Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutProductsInput[]
  updateMany?: Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutProductsInput | Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutProductsInput[]
  deleteMany?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
}

export type inventory_transaction_detailsUncheckedUpdateManyWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput> | Prisma.inventory_transaction_detailsCreateWithoutProductsInput[] | Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput | Prisma.inventory_transaction_detailsCreateOrConnectWithoutProductsInput[]
  upsert?: Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutProductsInput | Prisma.inventory_transaction_detailsUpsertWithWhereUniqueWithoutProductsInput[]
  createMany?: Prisma.inventory_transaction_detailsCreateManyProductsInputEnvelope
  set?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  disconnect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  delete?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  connect?: Prisma.inventory_transaction_detailsWhereUniqueInput | Prisma.inventory_transaction_detailsWhereUniqueInput[]
  update?: Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutProductsInput | Prisma.inventory_transaction_detailsUpdateWithWhereUniqueWithoutProductsInput[]
  updateMany?: Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutProductsInput | Prisma.inventory_transaction_detailsUpdateManyWithWhereWithoutProductsInput[]
  deleteMany?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
}

export type inventory_transaction_detailsCreateWithoutInventory_transactionsInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  materials?: Prisma.materialsCreateNestedOneWithoutInventory_transaction_detailsInput
  products?: Prisma.productsCreateNestedOneWithoutInventory_transaction_detailsInput
}

export type inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput = {
  id?: number
  product_id?: number | null
  material_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsCreateOrConnectWithoutInventory_transactionsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput>
}

export type inventory_transaction_detailsCreateManyInventory_transactionsInputEnvelope = {
  data: Prisma.inventory_transaction_detailsCreateManyInventory_transactionsInput | Prisma.inventory_transaction_detailsCreateManyInventory_transactionsInput[]
  skipDuplicates?: boolean
}

export type inventory_transaction_detailsUpsertWithWhereUniqueWithoutInventory_transactionsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  update: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedUpdateWithoutInventory_transactionsInput>
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutInventory_transactionsInput>
}

export type inventory_transaction_detailsUpdateWithWhereUniqueWithoutInventory_transactionsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateWithoutInventory_transactionsInput, Prisma.inventory_transaction_detailsUncheckedUpdateWithoutInventory_transactionsInput>
}

export type inventory_transaction_detailsUpdateManyWithWhereWithoutInventory_transactionsInput = {
  where: Prisma.inventory_transaction_detailsScalarWhereInput
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateManyMutationInput, Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutInventory_transactionsInput>
}

export type inventory_transaction_detailsScalarWhereInput = {
  AND?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
  OR?: Prisma.inventory_transaction_detailsScalarWhereInput[]
  NOT?: Prisma.inventory_transaction_detailsScalarWhereInput | Prisma.inventory_transaction_detailsScalarWhereInput[]
  id?: Prisma.IntFilter<"inventory_transaction_details"> | number
  transaction_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  product_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  material_id?: Prisma.IntNullableFilter<"inventory_transaction_details"> | number | null
  quantity?: Prisma.DecimalFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.DecimalNullableFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.DecimalNullableFilter<"inventory_transaction_details"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableFilter<"inventory_transaction_details"> | string | null
}

export type inventory_transaction_detailsCreateWithoutMaterialsInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  products?: Prisma.productsCreateNestedOneWithoutInventory_transaction_detailsInput
  inventory_transactions?: Prisma.inventory_transactionsCreateNestedOneWithoutInventory_transaction_detailsInput
}

export type inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput = {
  id?: number
  transaction_id?: number | null
  product_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsCreateOrConnectWithoutMaterialsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput>
}

export type inventory_transaction_detailsCreateManyMaterialsInputEnvelope = {
  data: Prisma.inventory_transaction_detailsCreateManyMaterialsInput | Prisma.inventory_transaction_detailsCreateManyMaterialsInput[]
  skipDuplicates?: boolean
}

export type inventory_transaction_detailsUpsertWithWhereUniqueWithoutMaterialsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  update: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedUpdateWithoutMaterialsInput>
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutMaterialsInput>
}

export type inventory_transaction_detailsUpdateWithWhereUniqueWithoutMaterialsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateWithoutMaterialsInput, Prisma.inventory_transaction_detailsUncheckedUpdateWithoutMaterialsInput>
}

export type inventory_transaction_detailsUpdateManyWithWhereWithoutMaterialsInput = {
  where: Prisma.inventory_transaction_detailsScalarWhereInput
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateManyMutationInput, Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsInput>
}

export type inventory_transaction_detailsCreateWithoutProductsInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  materials?: Prisma.materialsCreateNestedOneWithoutInventory_transaction_detailsInput
  inventory_transactions?: Prisma.inventory_transactionsCreateNestedOneWithoutInventory_transaction_detailsInput
}

export type inventory_transaction_detailsUncheckedCreateWithoutProductsInput = {
  id?: number
  transaction_id?: number | null
  material_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsCreateOrConnectWithoutProductsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput>
}

export type inventory_transaction_detailsCreateManyProductsInputEnvelope = {
  data: Prisma.inventory_transaction_detailsCreateManyProductsInput | Prisma.inventory_transaction_detailsCreateManyProductsInput[]
  skipDuplicates?: boolean
}

export type inventory_transaction_detailsUpsertWithWhereUniqueWithoutProductsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  update: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedCreateWithoutProductsInput>
}

export type inventory_transaction_detailsUpdateWithWhereUniqueWithoutProductsInput = {
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateWithoutProductsInput, Prisma.inventory_transaction_detailsUncheckedUpdateWithoutProductsInput>
}

export type inventory_transaction_detailsUpdateManyWithWhereWithoutProductsInput = {
  where: Prisma.inventory_transaction_detailsScalarWhereInput
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateManyMutationInput, Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutProductsInput>
}

export type inventory_transaction_detailsCreateManyInventory_transactionsInput = {
  id?: number
  product_id?: number | null
  material_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsUpdateWithoutInventory_transactionsInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  materials?: Prisma.materialsUpdateOneWithoutInventory_transaction_detailsNestedInput
  products?: Prisma.productsUpdateOneWithoutInventory_transaction_detailsNestedInput
}

export type inventory_transaction_detailsUncheckedUpdateWithoutInventory_transactionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  product_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  material_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsUncheckedUpdateManyWithoutInventory_transactionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  product_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  material_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsCreateManyMaterialsInput = {
  id?: number
  transaction_id?: number | null
  product_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsUpdateWithoutMaterialsInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  products?: Prisma.productsUpdateOneWithoutInventory_transaction_detailsNestedInput
  inventory_transactions?: Prisma.inventory_transactionsUpdateOneWithoutInventory_transaction_detailsNestedInput
}

export type inventory_transaction_detailsUncheckedUpdateWithoutMaterialsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  transaction_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  product_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  transaction_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  product_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsCreateManyProductsInput = {
  id?: number
  transaction_id?: number | null
  material_id?: number | null
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
}

export type inventory_transaction_detailsUpdateWithoutProductsInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  materials?: Prisma.materialsUpdateOneWithoutInventory_transaction_detailsNestedInput
  inventory_transactions?: Prisma.inventory_transactionsUpdateOneWithoutInventory_transaction_detailsNestedInput
}

export type inventory_transaction_detailsUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  transaction_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  material_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type inventory_transaction_detailsUncheckedUpdateManyWithoutProductsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  transaction_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  material_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unit_price?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_amount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type inventory_transaction_detailsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transaction_id?: boolean
  product_id?: boolean
  material_id?: boolean
  quantity?: boolean
  unit_price?: boolean
  total_amount?: boolean
  notes?: boolean
  materials?: boolean | Prisma.inventory_transaction_details$materialsArgs<ExtArgs>
  products?: boolean | Prisma.inventory_transaction_details$productsArgs<ExtArgs>
  inventory_transactions?: boolean | Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>
}, ExtArgs["result"]["inventory_transaction_details"]>

export type inventory_transaction_detailsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transaction_id?: boolean
  product_id?: boolean
  material_id?: boolean
  quantity?: boolean
  unit_price?: boolean
  total_amount?: boolean
  notes?: boolean
  materials?: boolean | Prisma.inventory_transaction_details$materialsArgs<ExtArgs>
  products?: boolean | Prisma.inventory_transaction_details$productsArgs<ExtArgs>
  inventory_transactions?: boolean | Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>
}, ExtArgs["result"]["inventory_transaction_details"]>

export type inventory_transaction_detailsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transaction_id?: boolean
  product_id?: boolean
  material_id?: boolean
  quantity?: boolean
  unit_price?: boolean
  total_amount?: boolean
  notes?: boolean
  materials?: boolean | Prisma.inventory_transaction_details$materialsArgs<ExtArgs>
  products?: boolean | Prisma.inventory_transaction_details$productsArgs<ExtArgs>
  inventory_transactions?: boolean | Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>
}, ExtArgs["result"]["inventory_transaction_details"]>

export type inventory_transaction_detailsSelectScalar = {
  id?: boolean
  transaction_id?: boolean
  product_id?: boolean
  material_id?: boolean
  quantity?: boolean
  unit_price?: boolean
  total_amount?: boolean
  notes?: boolean
}

export type inventory_transaction_detailsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "transaction_id" | "product_id" | "material_id" | "quantity" | "unit_price" | "total_amount" | "notes", ExtArgs["result"]["inventory_transaction_details"]>
export type inventory_transaction_detailsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  materials?: boolean | Prisma.inventory_transaction_details$materialsArgs<ExtArgs>
  products?: boolean | Prisma.inventory_transaction_details$productsArgs<ExtArgs>
  inventory_transactions?: boolean | Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>
}
export type inventory_transaction_detailsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  materials?: boolean | Prisma.inventory_transaction_details$materialsArgs<ExtArgs>
  products?: boolean | Prisma.inventory_transaction_details$productsArgs<ExtArgs>
  inventory_transactions?: boolean | Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>
}
export type inventory_transaction_detailsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  materials?: boolean | Prisma.inventory_transaction_details$materialsArgs<ExtArgs>
  products?: boolean | Prisma.inventory_transaction_details$productsArgs<ExtArgs>
  inventory_transactions?: boolean | Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>
}

export type $inventory_transaction_detailsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "inventory_transaction_details"
  objects: {
    materials: Prisma.$materialsPayload<ExtArgs> | null
    products: Prisma.$productsPayload<ExtArgs> | null
    inventory_transactions: Prisma.$inventory_transactionsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    transaction_id: number | null
    product_id: number | null
    material_id: number | null
    quantity: runtime.Decimal
    unit_price: runtime.Decimal | null
    total_amount: runtime.Decimal | null
    notes: string | null
  }, ExtArgs["result"]["inventory_transaction_details"]>
  composites: {}
}

export type inventory_transaction_detailsGetPayload<S extends boolean | null | undefined | inventory_transaction_detailsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload, S>

export type inventory_transaction_detailsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<inventory_transaction_detailsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Inventory_transaction_detailsCountAggregateInputType | true
  }

export interface inventory_transaction_detailsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['inventory_transaction_details'], meta: { name: 'inventory_transaction_details' } }
  /**
   * Find zero or one Inventory_transaction_details that matches the filter.
   * @param {inventory_transaction_detailsFindUniqueArgs} args - Arguments to find a Inventory_transaction_details
   * @example
   * // Get one Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends inventory_transaction_detailsFindUniqueArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Inventory_transaction_details that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {inventory_transaction_detailsFindUniqueOrThrowArgs} args - Arguments to find a Inventory_transaction_details
   * @example
   * // Get one Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends inventory_transaction_detailsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inventory_transaction_details that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inventory_transaction_detailsFindFirstArgs} args - Arguments to find a Inventory_transaction_details
   * @example
   * // Get one Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends inventory_transaction_detailsFindFirstArgs>(args?: Prisma.SelectSubset<T, inventory_transaction_detailsFindFirstArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inventory_transaction_details that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inventory_transaction_detailsFindFirstOrThrowArgs} args - Arguments to find a Inventory_transaction_details
   * @example
   * // Get one Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends inventory_transaction_detailsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, inventory_transaction_detailsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Inventory_transaction_details that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inventory_transaction_detailsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.findMany()
   * 
   * // Get first 10 Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inventory_transaction_detailsWithIdOnly = await prisma.inventory_transaction_details.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends inventory_transaction_detailsFindManyArgs>(args?: Prisma.SelectSubset<T, inventory_transaction_detailsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Inventory_transaction_details.
   * @param {inventory_transaction_detailsCreateArgs} args - Arguments to create a Inventory_transaction_details.
   * @example
   * // Create one Inventory_transaction_details
   * const Inventory_transaction_details = await prisma.inventory_transaction_details.create({
   *   data: {
   *     // ... data to create a Inventory_transaction_details
   *   }
   * })
   * 
   */
  create<T extends inventory_transaction_detailsCreateArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsCreateArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Inventory_transaction_details.
   * @param {inventory_transaction_detailsCreateManyArgs} args - Arguments to create many Inventory_transaction_details.
   * @example
   * // Create many Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends inventory_transaction_detailsCreateManyArgs>(args?: Prisma.SelectSubset<T, inventory_transaction_detailsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Inventory_transaction_details and returns the data saved in the database.
   * @param {inventory_transaction_detailsCreateManyAndReturnArgs} args - Arguments to create many Inventory_transaction_details.
   * @example
   * // Create many Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Inventory_transaction_details and only return the `id`
   * const inventory_transaction_detailsWithIdOnly = await prisma.inventory_transaction_details.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends inventory_transaction_detailsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, inventory_transaction_detailsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Inventory_transaction_details.
   * @param {inventory_transaction_detailsDeleteArgs} args - Arguments to delete one Inventory_transaction_details.
   * @example
   * // Delete one Inventory_transaction_details
   * const Inventory_transaction_details = await prisma.inventory_transaction_details.delete({
   *   where: {
   *     // ... filter to delete one Inventory_transaction_details
   *   }
   * })
   * 
   */
  delete<T extends inventory_transaction_detailsDeleteArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsDeleteArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Inventory_transaction_details.
   * @param {inventory_transaction_detailsUpdateArgs} args - Arguments to update one Inventory_transaction_details.
   * @example
   * // Update one Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends inventory_transaction_detailsUpdateArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsUpdateArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Inventory_transaction_details.
   * @param {inventory_transaction_detailsDeleteManyArgs} args - Arguments to filter Inventory_transaction_details to delete.
   * @example
   * // Delete a few Inventory_transaction_details
   * const { count } = await prisma.inventory_transaction_details.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends inventory_transaction_detailsDeleteManyArgs>(args?: Prisma.SelectSubset<T, inventory_transaction_detailsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inventory_transaction_details.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inventory_transaction_detailsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends inventory_transaction_detailsUpdateManyArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inventory_transaction_details and returns the data updated in the database.
   * @param {inventory_transaction_detailsUpdateManyAndReturnArgs} args - Arguments to update many Inventory_transaction_details.
   * @example
   * // Update many Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Inventory_transaction_details and only return the `id`
   * const inventory_transaction_detailsWithIdOnly = await prisma.inventory_transaction_details.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends inventory_transaction_detailsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Inventory_transaction_details.
   * @param {inventory_transaction_detailsUpsertArgs} args - Arguments to update or create a Inventory_transaction_details.
   * @example
   * // Update or create a Inventory_transaction_details
   * const inventory_transaction_details = await prisma.inventory_transaction_details.upsert({
   *   create: {
   *     // ... data to create a Inventory_transaction_details
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Inventory_transaction_details we want to update
   *   }
   * })
   */
  upsert<T extends inventory_transaction_detailsUpsertArgs>(args: Prisma.SelectSubset<T, inventory_transaction_detailsUpsertArgs<ExtArgs>>): Prisma.Prisma__inventory_transaction_detailsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Inventory_transaction_details.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inventory_transaction_detailsCountArgs} args - Arguments to filter Inventory_transaction_details to count.
   * @example
   * // Count the number of Inventory_transaction_details
   * const count = await prisma.inventory_transaction_details.count({
   *   where: {
   *     // ... the filter for the Inventory_transaction_details we want to count
   *   }
   * })
  **/
  count<T extends inventory_transaction_detailsCountArgs>(
    args?: Prisma.Subset<T, inventory_transaction_detailsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Inventory_transaction_detailsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Inventory_transaction_details.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Inventory_transaction_detailsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Inventory_transaction_detailsAggregateArgs>(args: Prisma.Subset<T, Inventory_transaction_detailsAggregateArgs>): Prisma.PrismaPromise<GetInventory_transaction_detailsAggregateType<T>>

  /**
   * Group by Inventory_transaction_details.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inventory_transaction_detailsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends inventory_transaction_detailsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: inventory_transaction_detailsGroupByArgs['orderBy'] }
      : { orderBy?: inventory_transaction_detailsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, inventory_transaction_detailsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInventory_transaction_detailsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the inventory_transaction_details model
 */
readonly fields: inventory_transaction_detailsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for inventory_transaction_details.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__inventory_transaction_detailsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  materials<T extends Prisma.inventory_transaction_details$materialsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.inventory_transaction_details$materialsArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  products<T extends Prisma.inventory_transaction_details$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.inventory_transaction_details$productsArgs<ExtArgs>>): Prisma.Prisma__productsClient<runtime.Types.Result.GetResult<Prisma.$productsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  inventory_transactions<T extends Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.inventory_transaction_details$inventory_transactionsArgs<ExtArgs>>): Prisma.Prisma__inventory_transactionsClient<runtime.Types.Result.GetResult<Prisma.$inventory_transactionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the inventory_transaction_details model
 */
export interface inventory_transaction_detailsFieldRefs {
  readonly id: Prisma.FieldRef<"inventory_transaction_details", 'Int'>
  readonly transaction_id: Prisma.FieldRef<"inventory_transaction_details", 'Int'>
  readonly product_id: Prisma.FieldRef<"inventory_transaction_details", 'Int'>
  readonly material_id: Prisma.FieldRef<"inventory_transaction_details", 'Int'>
  readonly quantity: Prisma.FieldRef<"inventory_transaction_details", 'Decimal'>
  readonly unit_price: Prisma.FieldRef<"inventory_transaction_details", 'Decimal'>
  readonly total_amount: Prisma.FieldRef<"inventory_transaction_details", 'Decimal'>
  readonly notes: Prisma.FieldRef<"inventory_transaction_details", 'String'>
}
    

// Custom InputTypes
/**
 * inventory_transaction_details findUnique
 */
export type inventory_transaction_detailsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * Filter, which inventory_transaction_details to fetch.
   */
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
}

/**
 * inventory_transaction_details findUniqueOrThrow
 */
export type inventory_transaction_detailsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * Filter, which inventory_transaction_details to fetch.
   */
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
}

/**
 * inventory_transaction_details findFirst
 */
export type inventory_transaction_detailsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * Filter, which inventory_transaction_details to fetch.
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inventory_transaction_details to fetch.
   */
  orderBy?: Prisma.inventory_transaction_detailsOrderByWithRelationInput | Prisma.inventory_transaction_detailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for inventory_transaction_details.
   */
  cursor?: Prisma.inventory_transaction_detailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inventory_transaction_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inventory_transaction_details.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of inventory_transaction_details.
   */
  distinct?: Prisma.Inventory_transaction_detailsScalarFieldEnum | Prisma.Inventory_transaction_detailsScalarFieldEnum[]
}

/**
 * inventory_transaction_details findFirstOrThrow
 */
export type inventory_transaction_detailsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * Filter, which inventory_transaction_details to fetch.
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inventory_transaction_details to fetch.
   */
  orderBy?: Prisma.inventory_transaction_detailsOrderByWithRelationInput | Prisma.inventory_transaction_detailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for inventory_transaction_details.
   */
  cursor?: Prisma.inventory_transaction_detailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inventory_transaction_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inventory_transaction_details.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of inventory_transaction_details.
   */
  distinct?: Prisma.Inventory_transaction_detailsScalarFieldEnum | Prisma.Inventory_transaction_detailsScalarFieldEnum[]
}

/**
 * inventory_transaction_details findMany
 */
export type inventory_transaction_detailsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * Filter, which inventory_transaction_details to fetch.
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inventory_transaction_details to fetch.
   */
  orderBy?: Prisma.inventory_transaction_detailsOrderByWithRelationInput | Prisma.inventory_transaction_detailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing inventory_transaction_details.
   */
  cursor?: Prisma.inventory_transaction_detailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inventory_transaction_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inventory_transaction_details.
   */
  skip?: number
  distinct?: Prisma.Inventory_transaction_detailsScalarFieldEnum | Prisma.Inventory_transaction_detailsScalarFieldEnum[]
}

/**
 * inventory_transaction_details create
 */
export type inventory_transaction_detailsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * The data needed to create a inventory_transaction_details.
   */
  data: Prisma.XOR<Prisma.inventory_transaction_detailsCreateInput, Prisma.inventory_transaction_detailsUncheckedCreateInput>
}

/**
 * inventory_transaction_details createMany
 */
export type inventory_transaction_detailsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many inventory_transaction_details.
   */
  data: Prisma.inventory_transaction_detailsCreateManyInput | Prisma.inventory_transaction_detailsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * inventory_transaction_details createManyAndReturn
 */
export type inventory_transaction_detailsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * The data used to create many inventory_transaction_details.
   */
  data: Prisma.inventory_transaction_detailsCreateManyInput | Prisma.inventory_transaction_detailsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * inventory_transaction_details update
 */
export type inventory_transaction_detailsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * The data needed to update a inventory_transaction_details.
   */
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateInput, Prisma.inventory_transaction_detailsUncheckedUpdateInput>
  /**
   * Choose, which inventory_transaction_details to update.
   */
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
}

/**
 * inventory_transaction_details updateMany
 */
export type inventory_transaction_detailsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update inventory_transaction_details.
   */
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateManyMutationInput, Prisma.inventory_transaction_detailsUncheckedUpdateManyInput>
  /**
   * Filter which inventory_transaction_details to update
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * Limit how many inventory_transaction_details to update.
   */
  limit?: number
}

/**
 * inventory_transaction_details updateManyAndReturn
 */
export type inventory_transaction_detailsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * The data used to update inventory_transaction_details.
   */
  data: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateManyMutationInput, Prisma.inventory_transaction_detailsUncheckedUpdateManyInput>
  /**
   * Filter which inventory_transaction_details to update
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * Limit how many inventory_transaction_details to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * inventory_transaction_details upsert
 */
export type inventory_transaction_detailsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * The filter to search for the inventory_transaction_details to update in case it exists.
   */
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
  /**
   * In case the inventory_transaction_details found by the `where` argument doesn't exist, create a new inventory_transaction_details with this data.
   */
  create: Prisma.XOR<Prisma.inventory_transaction_detailsCreateInput, Prisma.inventory_transaction_detailsUncheckedCreateInput>
  /**
   * In case the inventory_transaction_details was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.inventory_transaction_detailsUpdateInput, Prisma.inventory_transaction_detailsUncheckedUpdateInput>
}

/**
 * inventory_transaction_details delete
 */
export type inventory_transaction_detailsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  /**
   * Filter which inventory_transaction_details to delete.
   */
  where: Prisma.inventory_transaction_detailsWhereUniqueInput
}

/**
 * inventory_transaction_details deleteMany
 */
export type inventory_transaction_detailsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which inventory_transaction_details to delete
   */
  where?: Prisma.inventory_transaction_detailsWhereInput
  /**
   * Limit how many inventory_transaction_details to delete.
   */
  limit?: number
}

/**
 * inventory_transaction_details.materials
 */
export type inventory_transaction_details$materialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  where?: Prisma.materialsWhereInput
}

/**
 * inventory_transaction_details.products
 */
export type inventory_transaction_details$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the products
   */
  select?: Prisma.productsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the products
   */
  omit?: Prisma.productsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.productsInclude<ExtArgs> | null
  where?: Prisma.productsWhereInput
}

/**
 * inventory_transaction_details.inventory_transactions
 */
export type inventory_transaction_details$inventory_transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transactions
   */
  select?: Prisma.inventory_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transactions
   */
  omit?: Prisma.inventory_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transactionsInclude<ExtArgs> | null
  where?: Prisma.inventory_transactionsWhereInput
}

/**
 * inventory_transaction_details without action
 */
export type inventory_transaction_detailsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
}
