
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `materials` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model materials
 * 
 */
export type materialsModel = runtime.Types.Result.DefaultSelection<Prisma.$materialsPayload>

export type AggregateMaterials = {
  _count: MaterialsCountAggregateOutputType | null
  _avg: MaterialsAvgAggregateOutputType | null
  _sum: MaterialsSumAggregateOutputType | null
  _min: MaterialsMinAggregateOutputType | null
  _max: MaterialsMaxAggregateOutputType | null
}

export type MaterialsAvgAggregateOutputType = {
  id: number | null
  branch_id: number | null
}

export type MaterialsSumAggregateOutputType = {
  id: number | null
  branch_id: number | null
}

export type MaterialsMinAggregateOutputType = {
  id: number | null
  material_code: string | null
  material_name: string | null
  unit: string | null
  description: string | null
  branch_id: number | null
  created_at: Date | null
}

export type MaterialsMaxAggregateOutputType = {
  id: number | null
  material_code: string | null
  material_name: string | null
  unit: string | null
  description: string | null
  branch_id: number | null
  created_at: Date | null
}

export type MaterialsCountAggregateOutputType = {
  id: number
  material_code: number
  material_name: number
  unit: number
  description: number
  branch_id: number
  created_at: number
  _all: number
}


export type MaterialsAvgAggregateInputType = {
  id?: true
  branch_id?: true
}

export type MaterialsSumAggregateInputType = {
  id?: true
  branch_id?: true
}

export type MaterialsMinAggregateInputType = {
  id?: true
  material_code?: true
  material_name?: true
  unit?: true
  description?: true
  branch_id?: true
  created_at?: true
}

export type MaterialsMaxAggregateInputType = {
  id?: true
  material_code?: true
  material_name?: true
  unit?: true
  description?: true
  branch_id?: true
  created_at?: true
}

export type MaterialsCountAggregateInputType = {
  id?: true
  material_code?: true
  material_name?: true
  unit?: true
  description?: true
  branch_id?: true
  created_at?: true
  _all?: true
}

export type MaterialsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which materials to aggregate.
   */
  where?: Prisma.materialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of materials to fetch.
   */
  orderBy?: Prisma.materialsOrderByWithRelationInput | Prisma.materialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.materialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned materials
  **/
  _count?: true | MaterialsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaterialsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaterialsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaterialsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaterialsMaxAggregateInputType
}

export type GetMaterialsAggregateType<T extends MaterialsAggregateArgs> = {
      [P in keyof T & keyof AggregateMaterials]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaterials[P]>
    : Prisma.GetScalarType<T[P], AggregateMaterials[P]>
}




export type materialsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.materialsWhereInput
  orderBy?: Prisma.materialsOrderByWithAggregationInput | Prisma.materialsOrderByWithAggregationInput[]
  by: Prisma.MaterialsScalarFieldEnum[] | Prisma.MaterialsScalarFieldEnum
  having?: Prisma.materialsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaterialsCountAggregateInputType | true
  _avg?: MaterialsAvgAggregateInputType
  _sum?: MaterialsSumAggregateInputType
  _min?: MaterialsMinAggregateInputType
  _max?: MaterialsMaxAggregateInputType
}

export type MaterialsGroupByOutputType = {
  id: number
  material_code: string
  material_name: string
  unit: string
  description: string | null
  branch_id: number | null
  created_at: Date | null
  _count: MaterialsCountAggregateOutputType | null
  _avg: MaterialsAvgAggregateOutputType | null
  _sum: MaterialsSumAggregateOutputType | null
  _min: MaterialsMinAggregateOutputType | null
  _max: MaterialsMaxAggregateOutputType | null
}

type GetMaterialsGroupByPayload<T extends materialsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaterialsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaterialsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaterialsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaterialsGroupByOutputType[P]>
      }
    >
  >



export type materialsWhereInput = {
  AND?: Prisma.materialsWhereInput | Prisma.materialsWhereInput[]
  OR?: Prisma.materialsWhereInput[]
  NOT?: Prisma.materialsWhereInput | Prisma.materialsWhereInput[]
  id?: Prisma.IntFilter<"materials"> | number
  material_code?: Prisma.StringFilter<"materials"> | string
  material_name?: Prisma.StringFilter<"materials"> | string
  unit?: Prisma.StringFilter<"materials"> | string
  description?: Prisma.StringNullableFilter<"materials"> | string | null
  branch_id?: Prisma.IntNullableFilter<"materials"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"materials"> | Date | string | null
  bom?: Prisma.BomListRelationFilter
  goods?: Prisma.GoodsListRelationFilter
  inventory_balances?: Prisma.Inventory_balancesListRelationFilter
  inventory_transaction_details?: Prisma.Inventory_transaction_detailsListRelationFilter
  branches?: Prisma.XOR<Prisma.BranchesNullableScalarRelationFilter, Prisma.branchesWhereInput> | null
  purchase_order_details?: Prisma.Purchase_order_detailsListRelationFilter
}

export type materialsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  material_code?: Prisma.SortOrder
  material_name?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  branch_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  bom?: Prisma.bomOrderByRelationAggregateInput
  goods?: Prisma.goodsOrderByRelationAggregateInput
  inventory_balances?: Prisma.inventory_balancesOrderByRelationAggregateInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsOrderByRelationAggregateInput
  branches?: Prisma.branchesOrderByWithRelationInput
  purchase_order_details?: Prisma.purchase_order_detailsOrderByRelationAggregateInput
}

export type materialsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  material_code?: string
  AND?: Prisma.materialsWhereInput | Prisma.materialsWhereInput[]
  OR?: Prisma.materialsWhereInput[]
  NOT?: Prisma.materialsWhereInput | Prisma.materialsWhereInput[]
  material_name?: Prisma.StringFilter<"materials"> | string
  unit?: Prisma.StringFilter<"materials"> | string
  description?: Prisma.StringNullableFilter<"materials"> | string | null
  branch_id?: Prisma.IntNullableFilter<"materials"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"materials"> | Date | string | null
  bom?: Prisma.BomListRelationFilter
  goods?: Prisma.GoodsListRelationFilter
  inventory_balances?: Prisma.Inventory_balancesListRelationFilter
  inventory_transaction_details?: Prisma.Inventory_transaction_detailsListRelationFilter
  branches?: Prisma.XOR<Prisma.BranchesNullableScalarRelationFilter, Prisma.branchesWhereInput> | null
  purchase_order_details?: Prisma.Purchase_order_detailsListRelationFilter
}, "id" | "material_code">

export type materialsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  material_code?: Prisma.SortOrder
  material_name?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  branch_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.materialsCountOrderByAggregateInput
  _avg?: Prisma.materialsAvgOrderByAggregateInput
  _max?: Prisma.materialsMaxOrderByAggregateInput
  _min?: Prisma.materialsMinOrderByAggregateInput
  _sum?: Prisma.materialsSumOrderByAggregateInput
}

export type materialsScalarWhereWithAggregatesInput = {
  AND?: Prisma.materialsScalarWhereWithAggregatesInput | Prisma.materialsScalarWhereWithAggregatesInput[]
  OR?: Prisma.materialsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.materialsScalarWhereWithAggregatesInput | Prisma.materialsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"materials"> | number
  material_code?: Prisma.StringWithAggregatesFilter<"materials"> | string
  material_name?: Prisma.StringWithAggregatesFilter<"materials"> | string
  unit?: Prisma.StringWithAggregatesFilter<"materials"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"materials"> | string | null
  branch_id?: Prisma.IntNullableWithAggregatesFilter<"materials"> | number | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"materials"> | Date | string | null
}

export type materialsCreateInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput
  branches?: Prisma.branchesCreateNestedOneWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsCreateNestedManyWithoutMaterialsInput
}

export type materialsUncheckedCreateInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
  bom?: Prisma.bomUncheckedCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsUpdateInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput
  branches?: Prisma.branchesUpdateOneWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUncheckedUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsCreateManyInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
}

export type materialsUpdateManyMutationInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type materialsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MaterialsNullableScalarRelationFilter = {
  is?: Prisma.materialsWhereInput | null
  isNot?: Prisma.materialsWhereInput | null
}

export type MaterialsListRelationFilter = {
  every?: Prisma.materialsWhereInput
  some?: Prisma.materialsWhereInput
  none?: Prisma.materialsWhereInput
}

export type materialsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type materialsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  material_code?: Prisma.SortOrder
  material_name?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  description?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type materialsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
}

export type materialsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  material_code?: Prisma.SortOrder
  material_name?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  description?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type materialsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  material_code?: Prisma.SortOrder
  material_name?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  description?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type materialsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  branch_id?: Prisma.SortOrder
}

export type materialsCreateNestedOneWithoutBomInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutBomInput, Prisma.materialsUncheckedCreateWithoutBomInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutBomInput
  connect?: Prisma.materialsWhereUniqueInput
}

export type materialsUpdateOneWithoutBomNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutBomInput, Prisma.materialsUncheckedCreateWithoutBomInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutBomInput
  upsert?: Prisma.materialsUpsertWithoutBomInput
  disconnect?: Prisma.materialsWhereInput | boolean
  delete?: Prisma.materialsWhereInput | boolean
  connect?: Prisma.materialsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.materialsUpdateToOneWithWhereWithoutBomInput, Prisma.materialsUpdateWithoutBomInput>, Prisma.materialsUncheckedUpdateWithoutBomInput>
}

export type materialsCreateNestedOneWithoutGoodsInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutGoodsInput, Prisma.materialsUncheckedCreateWithoutGoodsInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutGoodsInput
  connect?: Prisma.materialsWhereUniqueInput
}

export type materialsUpdateOneWithoutGoodsNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutGoodsInput, Prisma.materialsUncheckedCreateWithoutGoodsInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutGoodsInput
  upsert?: Prisma.materialsUpsertWithoutGoodsInput
  disconnect?: Prisma.materialsWhereInput | boolean
  delete?: Prisma.materialsWhereInput | boolean
  connect?: Prisma.materialsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.materialsUpdateToOneWithWhereWithoutGoodsInput, Prisma.materialsUpdateWithoutGoodsInput>, Prisma.materialsUncheckedUpdateWithoutGoodsInput>
}

export type materialsCreateNestedManyWithoutBranchesInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutBranchesInput, Prisma.materialsUncheckedCreateWithoutBranchesInput> | Prisma.materialsCreateWithoutBranchesInput[] | Prisma.materialsUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutBranchesInput | Prisma.materialsCreateOrConnectWithoutBranchesInput[]
  createMany?: Prisma.materialsCreateManyBranchesInputEnvelope
  connect?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
}

export type materialsUncheckedCreateNestedManyWithoutBranchesInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutBranchesInput, Prisma.materialsUncheckedCreateWithoutBranchesInput> | Prisma.materialsCreateWithoutBranchesInput[] | Prisma.materialsUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutBranchesInput | Prisma.materialsCreateOrConnectWithoutBranchesInput[]
  createMany?: Prisma.materialsCreateManyBranchesInputEnvelope
  connect?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
}

export type materialsUpdateManyWithoutBranchesNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutBranchesInput, Prisma.materialsUncheckedCreateWithoutBranchesInput> | Prisma.materialsCreateWithoutBranchesInput[] | Prisma.materialsUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutBranchesInput | Prisma.materialsCreateOrConnectWithoutBranchesInput[]
  upsert?: Prisma.materialsUpsertWithWhereUniqueWithoutBranchesInput | Prisma.materialsUpsertWithWhereUniqueWithoutBranchesInput[]
  createMany?: Prisma.materialsCreateManyBranchesInputEnvelope
  set?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  disconnect?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  delete?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  connect?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  update?: Prisma.materialsUpdateWithWhereUniqueWithoutBranchesInput | Prisma.materialsUpdateWithWhereUniqueWithoutBranchesInput[]
  updateMany?: Prisma.materialsUpdateManyWithWhereWithoutBranchesInput | Prisma.materialsUpdateManyWithWhereWithoutBranchesInput[]
  deleteMany?: Prisma.materialsScalarWhereInput | Prisma.materialsScalarWhereInput[]
}

export type materialsUncheckedUpdateManyWithoutBranchesNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutBranchesInput, Prisma.materialsUncheckedCreateWithoutBranchesInput> | Prisma.materialsCreateWithoutBranchesInput[] | Prisma.materialsUncheckedCreateWithoutBranchesInput[]
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutBranchesInput | Prisma.materialsCreateOrConnectWithoutBranchesInput[]
  upsert?: Prisma.materialsUpsertWithWhereUniqueWithoutBranchesInput | Prisma.materialsUpsertWithWhereUniqueWithoutBranchesInput[]
  createMany?: Prisma.materialsCreateManyBranchesInputEnvelope
  set?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  disconnect?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  delete?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  connect?: Prisma.materialsWhereUniqueInput | Prisma.materialsWhereUniqueInput[]
  update?: Prisma.materialsUpdateWithWhereUniqueWithoutBranchesInput | Prisma.materialsUpdateWithWhereUniqueWithoutBranchesInput[]
  updateMany?: Prisma.materialsUpdateManyWithWhereWithoutBranchesInput | Prisma.materialsUpdateManyWithWhereWithoutBranchesInput[]
  deleteMany?: Prisma.materialsScalarWhereInput | Prisma.materialsScalarWhereInput[]
}

export type materialsCreateNestedOneWithoutInventory_balancesInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutInventory_balancesInput, Prisma.materialsUncheckedCreateWithoutInventory_balancesInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutInventory_balancesInput
  connect?: Prisma.materialsWhereUniqueInput
}

export type materialsUpdateOneWithoutInventory_balancesNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutInventory_balancesInput, Prisma.materialsUncheckedCreateWithoutInventory_balancesInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutInventory_balancesInput
  upsert?: Prisma.materialsUpsertWithoutInventory_balancesInput
  disconnect?: Prisma.materialsWhereInput | boolean
  delete?: Prisma.materialsWhereInput | boolean
  connect?: Prisma.materialsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.materialsUpdateToOneWithWhereWithoutInventory_balancesInput, Prisma.materialsUpdateWithoutInventory_balancesInput>, Prisma.materialsUncheckedUpdateWithoutInventory_balancesInput>
}

export type materialsCreateNestedOneWithoutInventory_transaction_detailsInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutInventory_transaction_detailsInput, Prisma.materialsUncheckedCreateWithoutInventory_transaction_detailsInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutInventory_transaction_detailsInput
  connect?: Prisma.materialsWhereUniqueInput
}

export type materialsUpdateOneWithoutInventory_transaction_detailsNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutInventory_transaction_detailsInput, Prisma.materialsUncheckedCreateWithoutInventory_transaction_detailsInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutInventory_transaction_detailsInput
  upsert?: Prisma.materialsUpsertWithoutInventory_transaction_detailsInput
  disconnect?: Prisma.materialsWhereInput | boolean
  delete?: Prisma.materialsWhereInput | boolean
  connect?: Prisma.materialsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.materialsUpdateToOneWithWhereWithoutInventory_transaction_detailsInput, Prisma.materialsUpdateWithoutInventory_transaction_detailsInput>, Prisma.materialsUncheckedUpdateWithoutInventory_transaction_detailsInput>
}

export type materialsCreateNestedOneWithoutPurchase_order_detailsInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutPurchase_order_detailsInput, Prisma.materialsUncheckedCreateWithoutPurchase_order_detailsInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutPurchase_order_detailsInput
  connect?: Prisma.materialsWhereUniqueInput
}

export type materialsUpdateOneWithoutPurchase_order_detailsNestedInput = {
  create?: Prisma.XOR<Prisma.materialsCreateWithoutPurchase_order_detailsInput, Prisma.materialsUncheckedCreateWithoutPurchase_order_detailsInput>
  connectOrCreate?: Prisma.materialsCreateOrConnectWithoutPurchase_order_detailsInput
  upsert?: Prisma.materialsUpsertWithoutPurchase_order_detailsInput
  disconnect?: Prisma.materialsWhereInput | boolean
  delete?: Prisma.materialsWhereInput | boolean
  connect?: Prisma.materialsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.materialsUpdateToOneWithWhereWithoutPurchase_order_detailsInput, Prisma.materialsUpdateWithoutPurchase_order_detailsInput>, Prisma.materialsUncheckedUpdateWithoutPurchase_order_detailsInput>
}

export type materialsCreateWithoutBomInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  goods?: Prisma.goodsCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput
  branches?: Prisma.branchesCreateNestedOneWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsCreateNestedManyWithoutMaterialsInput
}

export type materialsUncheckedCreateWithoutBomInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
  goods?: Prisma.goodsUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsCreateOrConnectWithoutBomInput = {
  where: Prisma.materialsWhereUniqueInput
  create: Prisma.XOR<Prisma.materialsCreateWithoutBomInput, Prisma.materialsUncheckedCreateWithoutBomInput>
}

export type materialsUpsertWithoutBomInput = {
  update: Prisma.XOR<Prisma.materialsUpdateWithoutBomInput, Prisma.materialsUncheckedUpdateWithoutBomInput>
  create: Prisma.XOR<Prisma.materialsCreateWithoutBomInput, Prisma.materialsUncheckedCreateWithoutBomInput>
  where?: Prisma.materialsWhereInput
}

export type materialsUpdateToOneWithWhereWithoutBomInput = {
  where?: Prisma.materialsWhereInput
  data: Prisma.XOR<Prisma.materialsUpdateWithoutBomInput, Prisma.materialsUncheckedUpdateWithoutBomInput>
}

export type materialsUpdateWithoutBomInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  goods?: Prisma.goodsUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput
  branches?: Prisma.branchesUpdateOneWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateWithoutBomInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  goods?: Prisma.goodsUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsCreateWithoutGoodsInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput
  branches?: Prisma.branchesCreateNestedOneWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsCreateNestedManyWithoutMaterialsInput
}

export type materialsUncheckedCreateWithoutGoodsInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
  bom?: Prisma.bomUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsCreateOrConnectWithoutGoodsInput = {
  where: Prisma.materialsWhereUniqueInput
  create: Prisma.XOR<Prisma.materialsCreateWithoutGoodsInput, Prisma.materialsUncheckedCreateWithoutGoodsInput>
}

export type materialsUpsertWithoutGoodsInput = {
  update: Prisma.XOR<Prisma.materialsUpdateWithoutGoodsInput, Prisma.materialsUncheckedUpdateWithoutGoodsInput>
  create: Prisma.XOR<Prisma.materialsCreateWithoutGoodsInput, Prisma.materialsUncheckedCreateWithoutGoodsInput>
  where?: Prisma.materialsWhereInput
}

export type materialsUpdateToOneWithWhereWithoutGoodsInput = {
  where?: Prisma.materialsWhereInput
  data: Prisma.XOR<Prisma.materialsUpdateWithoutGoodsInput, Prisma.materialsUncheckedUpdateWithoutGoodsInput>
}

export type materialsUpdateWithoutGoodsInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput
  branches?: Prisma.branchesUpdateOneWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateWithoutGoodsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsCreateWithoutBranchesInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsCreateNestedManyWithoutMaterialsInput
}

export type materialsUncheckedCreateWithoutBranchesInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomUncheckedCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsCreateOrConnectWithoutBranchesInput = {
  where: Prisma.materialsWhereUniqueInput
  create: Prisma.XOR<Prisma.materialsCreateWithoutBranchesInput, Prisma.materialsUncheckedCreateWithoutBranchesInput>
}

export type materialsCreateManyBranchesInputEnvelope = {
  data: Prisma.materialsCreateManyBranchesInput | Prisma.materialsCreateManyBranchesInput[]
  skipDuplicates?: boolean
}

export type materialsUpsertWithWhereUniqueWithoutBranchesInput = {
  where: Prisma.materialsWhereUniqueInput
  update: Prisma.XOR<Prisma.materialsUpdateWithoutBranchesInput, Prisma.materialsUncheckedUpdateWithoutBranchesInput>
  create: Prisma.XOR<Prisma.materialsCreateWithoutBranchesInput, Prisma.materialsUncheckedCreateWithoutBranchesInput>
}

export type materialsUpdateWithWhereUniqueWithoutBranchesInput = {
  where: Prisma.materialsWhereUniqueInput
  data: Prisma.XOR<Prisma.materialsUpdateWithoutBranchesInput, Prisma.materialsUncheckedUpdateWithoutBranchesInput>
}

export type materialsUpdateManyWithWhereWithoutBranchesInput = {
  where: Prisma.materialsScalarWhereInput
  data: Prisma.XOR<Prisma.materialsUpdateManyMutationInput, Prisma.materialsUncheckedUpdateManyWithoutBranchesInput>
}

export type materialsScalarWhereInput = {
  AND?: Prisma.materialsScalarWhereInput | Prisma.materialsScalarWhereInput[]
  OR?: Prisma.materialsScalarWhereInput[]
  NOT?: Prisma.materialsScalarWhereInput | Prisma.materialsScalarWhereInput[]
  id?: Prisma.IntFilter<"materials"> | number
  material_code?: Prisma.StringFilter<"materials"> | string
  material_name?: Prisma.StringFilter<"materials"> | string
  unit?: Prisma.StringFilter<"materials"> | string
  description?: Prisma.StringNullableFilter<"materials"> | string | null
  branch_id?: Prisma.IntNullableFilter<"materials"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"materials"> | Date | string | null
}

export type materialsCreateWithoutInventory_balancesInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput
  branches?: Prisma.branchesCreateNestedOneWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsCreateNestedManyWithoutMaterialsInput
}

export type materialsUncheckedCreateWithoutInventory_balancesInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
  bom?: Prisma.bomUncheckedCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsCreateOrConnectWithoutInventory_balancesInput = {
  where: Prisma.materialsWhereUniqueInput
  create: Prisma.XOR<Prisma.materialsCreateWithoutInventory_balancesInput, Prisma.materialsUncheckedCreateWithoutInventory_balancesInput>
}

export type materialsUpsertWithoutInventory_balancesInput = {
  update: Prisma.XOR<Prisma.materialsUpdateWithoutInventory_balancesInput, Prisma.materialsUncheckedUpdateWithoutInventory_balancesInput>
  create: Prisma.XOR<Prisma.materialsCreateWithoutInventory_balancesInput, Prisma.materialsUncheckedCreateWithoutInventory_balancesInput>
  where?: Prisma.materialsWhereInput
}

export type materialsUpdateToOneWithWhereWithoutInventory_balancesInput = {
  where?: Prisma.materialsWhereInput
  data: Prisma.XOR<Prisma.materialsUpdateWithoutInventory_balancesInput, Prisma.materialsUncheckedUpdateWithoutInventory_balancesInput>
}

export type materialsUpdateWithoutInventory_balancesInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput
  branches?: Prisma.branchesUpdateOneWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateWithoutInventory_balancesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUncheckedUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsCreateWithoutInventory_transaction_detailsInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesCreateNestedManyWithoutMaterialsInput
  branches?: Prisma.branchesCreateNestedOneWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsCreateNestedManyWithoutMaterialsInput
}

export type materialsUncheckedCreateWithoutInventory_transaction_detailsInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
  bom?: Prisma.bomUncheckedCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesUncheckedCreateNestedManyWithoutMaterialsInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsCreateOrConnectWithoutInventory_transaction_detailsInput = {
  where: Prisma.materialsWhereUniqueInput
  create: Prisma.XOR<Prisma.materialsCreateWithoutInventory_transaction_detailsInput, Prisma.materialsUncheckedCreateWithoutInventory_transaction_detailsInput>
}

export type materialsUpsertWithoutInventory_transaction_detailsInput = {
  update: Prisma.XOR<Prisma.materialsUpdateWithoutInventory_transaction_detailsInput, Prisma.materialsUncheckedUpdateWithoutInventory_transaction_detailsInput>
  create: Prisma.XOR<Prisma.materialsCreateWithoutInventory_transaction_detailsInput, Prisma.materialsUncheckedCreateWithoutInventory_transaction_detailsInput>
  where?: Prisma.materialsWhereInput
}

export type materialsUpdateToOneWithWhereWithoutInventory_transaction_detailsInput = {
  where?: Prisma.materialsWhereInput
  data: Prisma.XOR<Prisma.materialsUpdateWithoutInventory_transaction_detailsInput, Prisma.materialsUncheckedUpdateWithoutInventory_transaction_detailsInput>
}

export type materialsUpdateWithoutInventory_transaction_detailsInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUpdateManyWithoutMaterialsNestedInput
  branches?: Prisma.branchesUpdateOneWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateWithoutInventory_transaction_detailsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUncheckedUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUncheckedUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsCreateWithoutPurchase_order_detailsInput = {
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
  bom?: Prisma.bomCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsCreateNestedManyWithoutMaterialsInput
  branches?: Prisma.branchesCreateNestedOneWithoutMaterialsInput
}

export type materialsUncheckedCreateWithoutPurchase_order_detailsInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  branch_id?: number | null
  created_at?: Date | string | null
  bom?: Prisma.bomUncheckedCreateNestedManyWithoutMaterialsInput
  goods?: Prisma.goodsUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_balances?: Prisma.inventory_balancesUncheckedCreateNestedManyWithoutMaterialsInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedCreateNestedManyWithoutMaterialsInput
}

export type materialsCreateOrConnectWithoutPurchase_order_detailsInput = {
  where: Prisma.materialsWhereUniqueInput
  create: Prisma.XOR<Prisma.materialsCreateWithoutPurchase_order_detailsInput, Prisma.materialsUncheckedCreateWithoutPurchase_order_detailsInput>
}

export type materialsUpsertWithoutPurchase_order_detailsInput = {
  update: Prisma.XOR<Prisma.materialsUpdateWithoutPurchase_order_detailsInput, Prisma.materialsUncheckedUpdateWithoutPurchase_order_detailsInput>
  create: Prisma.XOR<Prisma.materialsCreateWithoutPurchase_order_detailsInput, Prisma.materialsUncheckedCreateWithoutPurchase_order_detailsInput>
  where?: Prisma.materialsWhereInput
}

export type materialsUpdateToOneWithWhereWithoutPurchase_order_detailsInput = {
  where?: Prisma.materialsWhereInput
  data: Prisma.XOR<Prisma.materialsUpdateWithoutPurchase_order_detailsInput, Prisma.materialsUncheckedUpdateWithoutPurchase_order_detailsInput>
}

export type materialsUpdateWithoutPurchase_order_detailsInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput
  branches?: Prisma.branchesUpdateOneWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateWithoutPurchase_order_detailsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  branch_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUncheckedUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsCreateManyBranchesInput = {
  id?: number
  material_code: string
  material_name: string
  unit: string
  description?: string | null
  created_at?: Date | string | null
}

export type materialsUpdateWithoutBranchesInput = {
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateWithoutBranchesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bom?: Prisma.bomUncheckedUpdateManyWithoutMaterialsNestedInput
  goods?: Prisma.goodsUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_balances?: Prisma.inventory_balancesUncheckedUpdateManyWithoutMaterialsNestedInput
  inventory_transaction_details?: Prisma.inventory_transaction_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
  purchase_order_details?: Prisma.purchase_order_detailsUncheckedUpdateManyWithoutMaterialsNestedInput
}

export type materialsUncheckedUpdateManyWithoutBranchesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  material_code?: Prisma.StringFieldUpdateOperationsInput | string
  material_name?: Prisma.StringFieldUpdateOperationsInput | string
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type MaterialsCountOutputType
 */

export type MaterialsCountOutputType = {
  bom: number
  goods: number
  inventory_balances: number
  inventory_transaction_details: number
  purchase_order_details: number
}

export type MaterialsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bom?: boolean | MaterialsCountOutputTypeCountBomArgs
  goods?: boolean | MaterialsCountOutputTypeCountGoodsArgs
  inventory_balances?: boolean | MaterialsCountOutputTypeCountInventory_balancesArgs
  inventory_transaction_details?: boolean | MaterialsCountOutputTypeCountInventory_transaction_detailsArgs
  purchase_order_details?: boolean | MaterialsCountOutputTypeCountPurchase_order_detailsArgs
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsCountOutputType
   */
  select?: Prisma.MaterialsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeCountBomArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.bomWhereInput
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeCountGoodsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.goodsWhereInput
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeCountInventory_balancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.inventory_balancesWhereInput
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeCountInventory_transaction_detailsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.inventory_transaction_detailsWhereInput
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeCountPurchase_order_detailsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.purchase_order_detailsWhereInput
}


export type materialsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  material_code?: boolean
  material_name?: boolean
  unit?: boolean
  description?: boolean
  branch_id?: boolean
  created_at?: boolean
  bom?: boolean | Prisma.materials$bomArgs<ExtArgs>
  goods?: boolean | Prisma.materials$goodsArgs<ExtArgs>
  inventory_balances?: boolean | Prisma.materials$inventory_balancesArgs<ExtArgs>
  inventory_transaction_details?: boolean | Prisma.materials$inventory_transaction_detailsArgs<ExtArgs>
  branches?: boolean | Prisma.materials$branchesArgs<ExtArgs>
  purchase_order_details?: boolean | Prisma.materials$purchase_order_detailsArgs<ExtArgs>
  _count?: boolean | Prisma.MaterialsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["materials"]>

export type materialsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  material_code?: boolean
  material_name?: boolean
  unit?: boolean
  description?: boolean
  branch_id?: boolean
  created_at?: boolean
  branches?: boolean | Prisma.materials$branchesArgs<ExtArgs>
}, ExtArgs["result"]["materials"]>

export type materialsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  material_code?: boolean
  material_name?: boolean
  unit?: boolean
  description?: boolean
  branch_id?: boolean
  created_at?: boolean
  branches?: boolean | Prisma.materials$branchesArgs<ExtArgs>
}, ExtArgs["result"]["materials"]>

export type materialsSelectScalar = {
  id?: boolean
  material_code?: boolean
  material_name?: boolean
  unit?: boolean
  description?: boolean
  branch_id?: boolean
  created_at?: boolean
}

export type materialsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "material_code" | "material_name" | "unit" | "description" | "branch_id" | "created_at", ExtArgs["result"]["materials"]>
export type materialsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bom?: boolean | Prisma.materials$bomArgs<ExtArgs>
  goods?: boolean | Prisma.materials$goodsArgs<ExtArgs>
  inventory_balances?: boolean | Prisma.materials$inventory_balancesArgs<ExtArgs>
  inventory_transaction_details?: boolean | Prisma.materials$inventory_transaction_detailsArgs<ExtArgs>
  branches?: boolean | Prisma.materials$branchesArgs<ExtArgs>
  purchase_order_details?: boolean | Prisma.materials$purchase_order_detailsArgs<ExtArgs>
  _count?: boolean | Prisma.MaterialsCountOutputTypeDefaultArgs<ExtArgs>
}
export type materialsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  branches?: boolean | Prisma.materials$branchesArgs<ExtArgs>
}
export type materialsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  branches?: boolean | Prisma.materials$branchesArgs<ExtArgs>
}

export type $materialsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "materials"
  objects: {
    bom: Prisma.$bomPayload<ExtArgs>[]
    goods: Prisma.$goodsPayload<ExtArgs>[]
    inventory_balances: Prisma.$inventory_balancesPayload<ExtArgs>[]
    inventory_transaction_details: Prisma.$inventory_transaction_detailsPayload<ExtArgs>[]
    branches: Prisma.$branchesPayload<ExtArgs> | null
    purchase_order_details: Prisma.$purchase_order_detailsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    material_code: string
    material_name: string
    unit: string
    description: string | null
    branch_id: number | null
    created_at: Date | null
  }, ExtArgs["result"]["materials"]>
  composites: {}
}

export type materialsGetPayload<S extends boolean | null | undefined | materialsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$materialsPayload, S>

export type materialsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<materialsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaterialsCountAggregateInputType | true
  }

export interface materialsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['materials'], meta: { name: 'materials' } }
  /**
   * Find zero or one Materials that matches the filter.
   * @param {materialsFindUniqueArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends materialsFindUniqueArgs>(args: Prisma.SelectSubset<T, materialsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Materials that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {materialsFindUniqueOrThrowArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends materialsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, materialsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Materials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {materialsFindFirstArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends materialsFindFirstArgs>(args?: Prisma.SelectSubset<T, materialsFindFirstArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Materials that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {materialsFindFirstOrThrowArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends materialsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, materialsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Materials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {materialsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Materials
   * const materials = await prisma.materials.findMany()
   * 
   * // Get first 10 Materials
   * const materials = await prisma.materials.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const materialsWithIdOnly = await prisma.materials.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends materialsFindManyArgs>(args?: Prisma.SelectSubset<T, materialsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Materials.
   * @param {materialsCreateArgs} args - Arguments to create a Materials.
   * @example
   * // Create one Materials
   * const Materials = await prisma.materials.create({
   *   data: {
   *     // ... data to create a Materials
   *   }
   * })
   * 
   */
  create<T extends materialsCreateArgs>(args: Prisma.SelectSubset<T, materialsCreateArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Materials.
   * @param {materialsCreateManyArgs} args - Arguments to create many Materials.
   * @example
   * // Create many Materials
   * const materials = await prisma.materials.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends materialsCreateManyArgs>(args?: Prisma.SelectSubset<T, materialsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Materials and returns the data saved in the database.
   * @param {materialsCreateManyAndReturnArgs} args - Arguments to create many Materials.
   * @example
   * // Create many Materials
   * const materials = await prisma.materials.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Materials and only return the `id`
   * const materialsWithIdOnly = await prisma.materials.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends materialsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, materialsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Materials.
   * @param {materialsDeleteArgs} args - Arguments to delete one Materials.
   * @example
   * // Delete one Materials
   * const Materials = await prisma.materials.delete({
   *   where: {
   *     // ... filter to delete one Materials
   *   }
   * })
   * 
   */
  delete<T extends materialsDeleteArgs>(args: Prisma.SelectSubset<T, materialsDeleteArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Materials.
   * @param {materialsUpdateArgs} args - Arguments to update one Materials.
   * @example
   * // Update one Materials
   * const materials = await prisma.materials.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends materialsUpdateArgs>(args: Prisma.SelectSubset<T, materialsUpdateArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Materials.
   * @param {materialsDeleteManyArgs} args - Arguments to filter Materials to delete.
   * @example
   * // Delete a few Materials
   * const { count } = await prisma.materials.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends materialsDeleteManyArgs>(args?: Prisma.SelectSubset<T, materialsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {materialsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Materials
   * const materials = await prisma.materials.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends materialsUpdateManyArgs>(args: Prisma.SelectSubset<T, materialsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Materials and returns the data updated in the database.
   * @param {materialsUpdateManyAndReturnArgs} args - Arguments to update many Materials.
   * @example
   * // Update many Materials
   * const materials = await prisma.materials.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Materials and only return the `id`
   * const materialsWithIdOnly = await prisma.materials.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends materialsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, materialsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Materials.
   * @param {materialsUpsertArgs} args - Arguments to update or create a Materials.
   * @example
   * // Update or create a Materials
   * const materials = await prisma.materials.upsert({
   *   create: {
   *     // ... data to create a Materials
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Materials we want to update
   *   }
   * })
   */
  upsert<T extends materialsUpsertArgs>(args: Prisma.SelectSubset<T, materialsUpsertArgs<ExtArgs>>): Prisma.Prisma__materialsClient<runtime.Types.Result.GetResult<Prisma.$materialsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {materialsCountArgs} args - Arguments to filter Materials to count.
   * @example
   * // Count the number of Materials
   * const count = await prisma.materials.count({
   *   where: {
   *     // ... the filter for the Materials we want to count
   *   }
   * })
  **/
  count<T extends materialsCountArgs>(
    args?: Prisma.Subset<T, materialsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaterialsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaterialsAggregateArgs>(args: Prisma.Subset<T, MaterialsAggregateArgs>): Prisma.PrismaPromise<GetMaterialsAggregateType<T>>

  /**
   * Group by Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {materialsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends materialsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: materialsGroupByArgs['orderBy'] }
      : { orderBy?: materialsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, materialsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaterialsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the materials model
 */
readonly fields: materialsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for materials.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__materialsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bom<T extends Prisma.materials$bomArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.materials$bomArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$bomPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  goods<T extends Prisma.materials$goodsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.materials$goodsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$goodsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  inventory_balances<T extends Prisma.materials$inventory_balancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.materials$inventory_balancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inventory_balancesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  inventory_transaction_details<T extends Prisma.materials$inventory_transaction_detailsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.materials$inventory_transaction_detailsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inventory_transaction_detailsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  branches<T extends Prisma.materials$branchesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.materials$branchesArgs<ExtArgs>>): Prisma.Prisma__branchesClient<runtime.Types.Result.GetResult<Prisma.$branchesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  purchase_order_details<T extends Prisma.materials$purchase_order_detailsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.materials$purchase_order_detailsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$purchase_order_detailsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the materials model
 */
export interface materialsFieldRefs {
  readonly id: Prisma.FieldRef<"materials", 'Int'>
  readonly material_code: Prisma.FieldRef<"materials", 'String'>
  readonly material_name: Prisma.FieldRef<"materials", 'String'>
  readonly unit: Prisma.FieldRef<"materials", 'String'>
  readonly description: Prisma.FieldRef<"materials", 'String'>
  readonly branch_id: Prisma.FieldRef<"materials", 'Int'>
  readonly created_at: Prisma.FieldRef<"materials", 'DateTime'>
}
    

// Custom InputTypes
/**
 * materials findUnique
 */
export type materialsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * Filter, which materials to fetch.
   */
  where: Prisma.materialsWhereUniqueInput
}

/**
 * materials findUniqueOrThrow
 */
export type materialsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * Filter, which materials to fetch.
   */
  where: Prisma.materialsWhereUniqueInput
}

/**
 * materials findFirst
 */
export type materialsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * Filter, which materials to fetch.
   */
  where?: Prisma.materialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of materials to fetch.
   */
  orderBy?: Prisma.materialsOrderByWithRelationInput | Prisma.materialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for materials.
   */
  cursor?: Prisma.materialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of materials.
   */
  distinct?: Prisma.MaterialsScalarFieldEnum | Prisma.MaterialsScalarFieldEnum[]
}

/**
 * materials findFirstOrThrow
 */
export type materialsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * Filter, which materials to fetch.
   */
  where?: Prisma.materialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of materials to fetch.
   */
  orderBy?: Prisma.materialsOrderByWithRelationInput | Prisma.materialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for materials.
   */
  cursor?: Prisma.materialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of materials.
   */
  distinct?: Prisma.MaterialsScalarFieldEnum | Prisma.MaterialsScalarFieldEnum[]
}

/**
 * materials findMany
 */
export type materialsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * Filter, which materials to fetch.
   */
  where?: Prisma.materialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of materials to fetch.
   */
  orderBy?: Prisma.materialsOrderByWithRelationInput | Prisma.materialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing materials.
   */
  cursor?: Prisma.materialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` materials.
   */
  skip?: number
  distinct?: Prisma.MaterialsScalarFieldEnum | Prisma.MaterialsScalarFieldEnum[]
}

/**
 * materials create
 */
export type materialsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * The data needed to create a materials.
   */
  data: Prisma.XOR<Prisma.materialsCreateInput, Prisma.materialsUncheckedCreateInput>
}

/**
 * materials createMany
 */
export type materialsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many materials.
   */
  data: Prisma.materialsCreateManyInput | Prisma.materialsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * materials createManyAndReturn
 */
export type materialsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * The data used to create many materials.
   */
  data: Prisma.materialsCreateManyInput | Prisma.materialsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * materials update
 */
export type materialsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * The data needed to update a materials.
   */
  data: Prisma.XOR<Prisma.materialsUpdateInput, Prisma.materialsUncheckedUpdateInput>
  /**
   * Choose, which materials to update.
   */
  where: Prisma.materialsWhereUniqueInput
}

/**
 * materials updateMany
 */
export type materialsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update materials.
   */
  data: Prisma.XOR<Prisma.materialsUpdateManyMutationInput, Prisma.materialsUncheckedUpdateManyInput>
  /**
   * Filter which materials to update
   */
  where?: Prisma.materialsWhereInput
  /**
   * Limit how many materials to update.
   */
  limit?: number
}

/**
 * materials updateManyAndReturn
 */
export type materialsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * The data used to update materials.
   */
  data: Prisma.XOR<Prisma.materialsUpdateManyMutationInput, Prisma.materialsUncheckedUpdateManyInput>
  /**
   * Filter which materials to update
   */
  where?: Prisma.materialsWhereInput
  /**
   * Limit how many materials to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * materials upsert
 */
export type materialsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * The filter to search for the materials to update in case it exists.
   */
  where: Prisma.materialsWhereUniqueInput
  /**
   * In case the materials found by the `where` argument doesn't exist, create a new materials with this data.
   */
  create: Prisma.XOR<Prisma.materialsCreateInput, Prisma.materialsUncheckedCreateInput>
  /**
   * In case the materials was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.materialsUpdateInput, Prisma.materialsUncheckedUpdateInput>
}

/**
 * materials delete
 */
export type materialsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
  /**
   * Filter which materials to delete.
   */
  where: Prisma.materialsWhereUniqueInput
}

/**
 * materials deleteMany
 */
export type materialsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which materials to delete
   */
  where?: Prisma.materialsWhereInput
  /**
   * Limit how many materials to delete.
   */
  limit?: number
}

/**
 * materials.bom
 */
export type materials$bomArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bom
   */
  select?: Prisma.bomSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bom
   */
  omit?: Prisma.bomOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bomInclude<ExtArgs> | null
  where?: Prisma.bomWhereInput
  orderBy?: Prisma.bomOrderByWithRelationInput | Prisma.bomOrderByWithRelationInput[]
  cursor?: Prisma.bomWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BomScalarFieldEnum | Prisma.BomScalarFieldEnum[]
}

/**
 * materials.goods
 */
export type materials$goodsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the goods
   */
  select?: Prisma.goodsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the goods
   */
  omit?: Prisma.goodsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.goodsInclude<ExtArgs> | null
  where?: Prisma.goodsWhereInput
  orderBy?: Prisma.goodsOrderByWithRelationInput | Prisma.goodsOrderByWithRelationInput[]
  cursor?: Prisma.goodsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GoodsScalarFieldEnum | Prisma.GoodsScalarFieldEnum[]
}

/**
 * materials.inventory_balances
 */
export type materials$inventory_balancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_balances
   */
  select?: Prisma.inventory_balancesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_balances
   */
  omit?: Prisma.inventory_balancesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_balancesInclude<ExtArgs> | null
  where?: Prisma.inventory_balancesWhereInput
  orderBy?: Prisma.inventory_balancesOrderByWithRelationInput | Prisma.inventory_balancesOrderByWithRelationInput[]
  cursor?: Prisma.inventory_balancesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Inventory_balancesScalarFieldEnum | Prisma.Inventory_balancesScalarFieldEnum[]
}

/**
 * materials.inventory_transaction_details
 */
export type materials$inventory_transaction_detailsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inventory_transaction_details
   */
  select?: Prisma.inventory_transaction_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inventory_transaction_details
   */
  omit?: Prisma.inventory_transaction_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inventory_transaction_detailsInclude<ExtArgs> | null
  where?: Prisma.inventory_transaction_detailsWhereInput
  orderBy?: Prisma.inventory_transaction_detailsOrderByWithRelationInput | Prisma.inventory_transaction_detailsOrderByWithRelationInput[]
  cursor?: Prisma.inventory_transaction_detailsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Inventory_transaction_detailsScalarFieldEnum | Prisma.Inventory_transaction_detailsScalarFieldEnum[]
}

/**
 * materials.branches
 */
export type materials$branchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the branches
   */
  select?: Prisma.branchesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the branches
   */
  omit?: Prisma.branchesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.branchesInclude<ExtArgs> | null
  where?: Prisma.branchesWhereInput
}

/**
 * materials.purchase_order_details
 */
export type materials$purchase_order_detailsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the purchase_order_details
   */
  select?: Prisma.purchase_order_detailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the purchase_order_details
   */
  omit?: Prisma.purchase_order_detailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.purchase_order_detailsInclude<ExtArgs> | null
  where?: Prisma.purchase_order_detailsWhereInput
  orderBy?: Prisma.purchase_order_detailsOrderByWithRelationInput | Prisma.purchase_order_detailsOrderByWithRelationInput[]
  cursor?: Prisma.purchase_order_detailsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Purchase_order_detailsScalarFieldEnum | Prisma.Purchase_order_detailsScalarFieldEnum[]
}

/**
 * materials without action
 */
export type materialsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the materials
   */
  select?: Prisma.materialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the materials
   */
  omit?: Prisma.materialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.materialsInclude<ExtArgs> | null
}
