
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `supplier_groups` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model supplier_groups
 * 
 */
export type supplier_groupsModel = runtime.Types.Result.DefaultSelection<Prisma.$supplier_groupsPayload>

export type AggregateSupplier_groups = {
  _count: Supplier_groupsCountAggregateOutputType | null
  _avg: Supplier_groupsAvgAggregateOutputType | null
  _sum: Supplier_groupsSumAggregateOutputType | null
  _min: Supplier_groupsMinAggregateOutputType | null
  _max: Supplier_groupsMaxAggregateOutputType | null
}

export type Supplier_groupsAvgAggregateOutputType = {
  id: number | null
}

export type Supplier_groupsSumAggregateOutputType = {
  id: number | null
}

export type Supplier_groupsMinAggregateOutputType = {
  id: number | null
  group_code: string | null
  group_name: string | null
  description: string | null
  created_at: Date | null
}

export type Supplier_groupsMaxAggregateOutputType = {
  id: number | null
  group_code: string | null
  group_name: string | null
  description: string | null
  created_at: Date | null
}

export type Supplier_groupsCountAggregateOutputType = {
  id: number
  group_code: number
  group_name: number
  description: number
  created_at: number
  _all: number
}


export type Supplier_groupsAvgAggregateInputType = {
  id?: true
}

export type Supplier_groupsSumAggregateInputType = {
  id?: true
}

export type Supplier_groupsMinAggregateInputType = {
  id?: true
  group_code?: true
  group_name?: true
  description?: true
  created_at?: true
}

export type Supplier_groupsMaxAggregateInputType = {
  id?: true
  group_code?: true
  group_name?: true
  description?: true
  created_at?: true
}

export type Supplier_groupsCountAggregateInputType = {
  id?: true
  group_code?: true
  group_name?: true
  description?: true
  created_at?: true
  _all?: true
}

export type Supplier_groupsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which supplier_groups to aggregate.
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of supplier_groups to fetch.
   */
  orderBy?: Prisma.supplier_groupsOrderByWithRelationInput | Prisma.supplier_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.supplier_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` supplier_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` supplier_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned supplier_groups
  **/
  _count?: true | Supplier_groupsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Supplier_groupsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Supplier_groupsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Supplier_groupsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Supplier_groupsMaxAggregateInputType
}

export type GetSupplier_groupsAggregateType<T extends Supplier_groupsAggregateArgs> = {
      [P in keyof T & keyof AggregateSupplier_groups]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSupplier_groups[P]>
    : Prisma.GetScalarType<T[P], AggregateSupplier_groups[P]>
}




export type supplier_groupsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.supplier_groupsWhereInput
  orderBy?: Prisma.supplier_groupsOrderByWithAggregationInput | Prisma.supplier_groupsOrderByWithAggregationInput[]
  by: Prisma.Supplier_groupsScalarFieldEnum[] | Prisma.Supplier_groupsScalarFieldEnum
  having?: Prisma.supplier_groupsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Supplier_groupsCountAggregateInputType | true
  _avg?: Supplier_groupsAvgAggregateInputType
  _sum?: Supplier_groupsSumAggregateInputType
  _min?: Supplier_groupsMinAggregateInputType
  _max?: Supplier_groupsMaxAggregateInputType
}

export type Supplier_groupsGroupByOutputType = {
  id: number
  group_code: string
  group_name: string
  description: string | null
  created_at: Date | null
  _count: Supplier_groupsCountAggregateOutputType | null
  _avg: Supplier_groupsAvgAggregateOutputType | null
  _sum: Supplier_groupsSumAggregateOutputType | null
  _min: Supplier_groupsMinAggregateOutputType | null
  _max: Supplier_groupsMaxAggregateOutputType | null
}

type GetSupplier_groupsGroupByPayload<T extends supplier_groupsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Supplier_groupsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Supplier_groupsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Supplier_groupsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Supplier_groupsGroupByOutputType[P]>
      }
    >
  >



export type supplier_groupsWhereInput = {
  AND?: Prisma.supplier_groupsWhereInput | Prisma.supplier_groupsWhereInput[]
  OR?: Prisma.supplier_groupsWhereInput[]
  NOT?: Prisma.supplier_groupsWhereInput | Prisma.supplier_groupsWhereInput[]
  id?: Prisma.IntFilter<"supplier_groups"> | number
  group_code?: Prisma.StringFilter<"supplier_groups"> | string
  group_name?: Prisma.StringFilter<"supplier_groups"> | string
  description?: Prisma.StringNullableFilter<"supplier_groups"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"supplier_groups"> | Date | string | null
  suppliers?: Prisma.SuppliersListRelationFilter
}

export type supplier_groupsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  suppliers?: Prisma.suppliersOrderByRelationAggregateInput
}

export type supplier_groupsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  group_code?: string
  AND?: Prisma.supplier_groupsWhereInput | Prisma.supplier_groupsWhereInput[]
  OR?: Prisma.supplier_groupsWhereInput[]
  NOT?: Prisma.supplier_groupsWhereInput | Prisma.supplier_groupsWhereInput[]
  group_name?: Prisma.StringFilter<"supplier_groups"> | string
  description?: Prisma.StringNullableFilter<"supplier_groups"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"supplier_groups"> | Date | string | null
  suppliers?: Prisma.SuppliersListRelationFilter
}, "id" | "group_code">

export type supplier_groupsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.supplier_groupsCountOrderByAggregateInput
  _avg?: Prisma.supplier_groupsAvgOrderByAggregateInput
  _max?: Prisma.supplier_groupsMaxOrderByAggregateInput
  _min?: Prisma.supplier_groupsMinOrderByAggregateInput
  _sum?: Prisma.supplier_groupsSumOrderByAggregateInput
}

export type supplier_groupsScalarWhereWithAggregatesInput = {
  AND?: Prisma.supplier_groupsScalarWhereWithAggregatesInput | Prisma.supplier_groupsScalarWhereWithAggregatesInput[]
  OR?: Prisma.supplier_groupsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.supplier_groupsScalarWhereWithAggregatesInput | Prisma.supplier_groupsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"supplier_groups"> | number
  group_code?: Prisma.StringWithAggregatesFilter<"supplier_groups"> | string
  group_name?: Prisma.StringWithAggregatesFilter<"supplier_groups"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"supplier_groups"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"supplier_groups"> | Date | string | null
}

export type supplier_groupsCreateInput = {
  group_code: string
  group_name: string
  description?: string | null
  created_at?: Date | string | null
  suppliers?: Prisma.suppliersCreateNestedManyWithoutSupplier_groupsInput
}

export type supplier_groupsUncheckedCreateInput = {
  id?: number
  group_code: string
  group_name: string
  description?: string | null
  created_at?: Date | string | null
  suppliers?: Prisma.suppliersUncheckedCreateNestedManyWithoutSupplier_groupsInput
}

export type supplier_groupsUpdateInput = {
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  suppliers?: Prisma.suppliersUpdateManyWithoutSupplier_groupsNestedInput
}

export type supplier_groupsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  suppliers?: Prisma.suppliersUncheckedUpdateManyWithoutSupplier_groupsNestedInput
}

export type supplier_groupsCreateManyInput = {
  id?: number
  group_code: string
  group_name: string
  description?: string | null
  created_at?: Date | string | null
}

export type supplier_groupsUpdateManyMutationInput = {
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type supplier_groupsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type supplier_groupsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type supplier_groupsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type supplier_groupsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type supplier_groupsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type supplier_groupsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type Supplier_groupsNullableScalarRelationFilter = {
  is?: Prisma.supplier_groupsWhereInput | null
  isNot?: Prisma.supplier_groupsWhereInput | null
}

export type supplier_groupsCreateNestedOneWithoutSuppliersInput = {
  create?: Prisma.XOR<Prisma.supplier_groupsCreateWithoutSuppliersInput, Prisma.supplier_groupsUncheckedCreateWithoutSuppliersInput>
  connectOrCreate?: Prisma.supplier_groupsCreateOrConnectWithoutSuppliersInput
  connect?: Prisma.supplier_groupsWhereUniqueInput
}

export type supplier_groupsUpdateOneWithoutSuppliersNestedInput = {
  create?: Prisma.XOR<Prisma.supplier_groupsCreateWithoutSuppliersInput, Prisma.supplier_groupsUncheckedCreateWithoutSuppliersInput>
  connectOrCreate?: Prisma.supplier_groupsCreateOrConnectWithoutSuppliersInput
  upsert?: Prisma.supplier_groupsUpsertWithoutSuppliersInput
  disconnect?: Prisma.supplier_groupsWhereInput | boolean
  delete?: Prisma.supplier_groupsWhereInput | boolean
  connect?: Prisma.supplier_groupsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.supplier_groupsUpdateToOneWithWhereWithoutSuppliersInput, Prisma.supplier_groupsUpdateWithoutSuppliersInput>, Prisma.supplier_groupsUncheckedUpdateWithoutSuppliersInput>
}

export type supplier_groupsCreateWithoutSuppliersInput = {
  group_code: string
  group_name: string
  description?: string | null
  created_at?: Date | string | null
}

export type supplier_groupsUncheckedCreateWithoutSuppliersInput = {
  id?: number
  group_code: string
  group_name: string
  description?: string | null
  created_at?: Date | string | null
}

export type supplier_groupsCreateOrConnectWithoutSuppliersInput = {
  where: Prisma.supplier_groupsWhereUniqueInput
  create: Prisma.XOR<Prisma.supplier_groupsCreateWithoutSuppliersInput, Prisma.supplier_groupsUncheckedCreateWithoutSuppliersInput>
}

export type supplier_groupsUpsertWithoutSuppliersInput = {
  update: Prisma.XOR<Prisma.supplier_groupsUpdateWithoutSuppliersInput, Prisma.supplier_groupsUncheckedUpdateWithoutSuppliersInput>
  create: Prisma.XOR<Prisma.supplier_groupsCreateWithoutSuppliersInput, Prisma.supplier_groupsUncheckedCreateWithoutSuppliersInput>
  where?: Prisma.supplier_groupsWhereInput
}

export type supplier_groupsUpdateToOneWithWhereWithoutSuppliersInput = {
  where?: Prisma.supplier_groupsWhereInput
  data: Prisma.XOR<Prisma.supplier_groupsUpdateWithoutSuppliersInput, Prisma.supplier_groupsUncheckedUpdateWithoutSuppliersInput>
}

export type supplier_groupsUpdateWithoutSuppliersInput = {
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type supplier_groupsUncheckedUpdateWithoutSuppliersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type Supplier_groupsCountOutputType
 */

export type Supplier_groupsCountOutputType = {
  suppliers: number
}

export type Supplier_groupsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  suppliers?: boolean | Supplier_groupsCountOutputTypeCountSuppliersArgs
}

/**
 * Supplier_groupsCountOutputType without action
 */
export type Supplier_groupsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Supplier_groupsCountOutputType
   */
  select?: Prisma.Supplier_groupsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Supplier_groupsCountOutputType without action
 */
export type Supplier_groupsCountOutputTypeCountSuppliersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.suppliersWhereInput
}


export type supplier_groupsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  group_code?: boolean
  group_name?: boolean
  description?: boolean
  created_at?: boolean
  suppliers?: boolean | Prisma.supplier_groups$suppliersArgs<ExtArgs>
  _count?: boolean | Prisma.Supplier_groupsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["supplier_groups"]>

export type supplier_groupsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  group_code?: boolean
  group_name?: boolean
  description?: boolean
  created_at?: boolean
}, ExtArgs["result"]["supplier_groups"]>

export type supplier_groupsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  group_code?: boolean
  group_name?: boolean
  description?: boolean
  created_at?: boolean
}, ExtArgs["result"]["supplier_groups"]>

export type supplier_groupsSelectScalar = {
  id?: boolean
  group_code?: boolean
  group_name?: boolean
  description?: boolean
  created_at?: boolean
}

export type supplier_groupsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "group_code" | "group_name" | "description" | "created_at", ExtArgs["result"]["supplier_groups"]>
export type supplier_groupsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  suppliers?: boolean | Prisma.supplier_groups$suppliersArgs<ExtArgs>
  _count?: boolean | Prisma.Supplier_groupsCountOutputTypeDefaultArgs<ExtArgs>
}
export type supplier_groupsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type supplier_groupsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $supplier_groupsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "supplier_groups"
  objects: {
    suppliers: Prisma.$suppliersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    group_code: string
    group_name: string
    description: string | null
    created_at: Date | null
  }, ExtArgs["result"]["supplier_groups"]>
  composites: {}
}

export type supplier_groupsGetPayload<S extends boolean | null | undefined | supplier_groupsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload, S>

export type supplier_groupsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<supplier_groupsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Supplier_groupsCountAggregateInputType | true
  }

export interface supplier_groupsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['supplier_groups'], meta: { name: 'supplier_groups' } }
  /**
   * Find zero or one Supplier_groups that matches the filter.
   * @param {supplier_groupsFindUniqueArgs} args - Arguments to find a Supplier_groups
   * @example
   * // Get one Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends supplier_groupsFindUniqueArgs>(args: Prisma.SelectSubset<T, supplier_groupsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Supplier_groups that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {supplier_groupsFindUniqueOrThrowArgs} args - Arguments to find a Supplier_groups
   * @example
   * // Get one Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends supplier_groupsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, supplier_groupsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Supplier_groups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {supplier_groupsFindFirstArgs} args - Arguments to find a Supplier_groups
   * @example
   * // Get one Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends supplier_groupsFindFirstArgs>(args?: Prisma.SelectSubset<T, supplier_groupsFindFirstArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Supplier_groups that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {supplier_groupsFindFirstOrThrowArgs} args - Arguments to find a Supplier_groups
   * @example
   * // Get one Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends supplier_groupsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, supplier_groupsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Supplier_groups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {supplier_groupsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.findMany()
   * 
   * // Get first 10 Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const supplier_groupsWithIdOnly = await prisma.supplier_groups.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends supplier_groupsFindManyArgs>(args?: Prisma.SelectSubset<T, supplier_groupsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Supplier_groups.
   * @param {supplier_groupsCreateArgs} args - Arguments to create a Supplier_groups.
   * @example
   * // Create one Supplier_groups
   * const Supplier_groups = await prisma.supplier_groups.create({
   *   data: {
   *     // ... data to create a Supplier_groups
   *   }
   * })
   * 
   */
  create<T extends supplier_groupsCreateArgs>(args: Prisma.SelectSubset<T, supplier_groupsCreateArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Supplier_groups.
   * @param {supplier_groupsCreateManyArgs} args - Arguments to create many Supplier_groups.
   * @example
   * // Create many Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends supplier_groupsCreateManyArgs>(args?: Prisma.SelectSubset<T, supplier_groupsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Supplier_groups and returns the data saved in the database.
   * @param {supplier_groupsCreateManyAndReturnArgs} args - Arguments to create many Supplier_groups.
   * @example
   * // Create many Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Supplier_groups and only return the `id`
   * const supplier_groupsWithIdOnly = await prisma.supplier_groups.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends supplier_groupsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, supplier_groupsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Supplier_groups.
   * @param {supplier_groupsDeleteArgs} args - Arguments to delete one Supplier_groups.
   * @example
   * // Delete one Supplier_groups
   * const Supplier_groups = await prisma.supplier_groups.delete({
   *   where: {
   *     // ... filter to delete one Supplier_groups
   *   }
   * })
   * 
   */
  delete<T extends supplier_groupsDeleteArgs>(args: Prisma.SelectSubset<T, supplier_groupsDeleteArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Supplier_groups.
   * @param {supplier_groupsUpdateArgs} args - Arguments to update one Supplier_groups.
   * @example
   * // Update one Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends supplier_groupsUpdateArgs>(args: Prisma.SelectSubset<T, supplier_groupsUpdateArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Supplier_groups.
   * @param {supplier_groupsDeleteManyArgs} args - Arguments to filter Supplier_groups to delete.
   * @example
   * // Delete a few Supplier_groups
   * const { count } = await prisma.supplier_groups.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends supplier_groupsDeleteManyArgs>(args?: Prisma.SelectSubset<T, supplier_groupsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Supplier_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {supplier_groupsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends supplier_groupsUpdateManyArgs>(args: Prisma.SelectSubset<T, supplier_groupsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Supplier_groups and returns the data updated in the database.
   * @param {supplier_groupsUpdateManyAndReturnArgs} args - Arguments to update many Supplier_groups.
   * @example
   * // Update many Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Supplier_groups and only return the `id`
   * const supplier_groupsWithIdOnly = await prisma.supplier_groups.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends supplier_groupsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, supplier_groupsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Supplier_groups.
   * @param {supplier_groupsUpsertArgs} args - Arguments to update or create a Supplier_groups.
   * @example
   * // Update or create a Supplier_groups
   * const supplier_groups = await prisma.supplier_groups.upsert({
   *   create: {
   *     // ... data to create a Supplier_groups
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Supplier_groups we want to update
   *   }
   * })
   */
  upsert<T extends supplier_groupsUpsertArgs>(args: Prisma.SelectSubset<T, supplier_groupsUpsertArgs<ExtArgs>>): Prisma.Prisma__supplier_groupsClient<runtime.Types.Result.GetResult<Prisma.$supplier_groupsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Supplier_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {supplier_groupsCountArgs} args - Arguments to filter Supplier_groups to count.
   * @example
   * // Count the number of Supplier_groups
   * const count = await prisma.supplier_groups.count({
   *   where: {
   *     // ... the filter for the Supplier_groups we want to count
   *   }
   * })
  **/
  count<T extends supplier_groupsCountArgs>(
    args?: Prisma.Subset<T, supplier_groupsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Supplier_groupsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Supplier_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Supplier_groupsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Supplier_groupsAggregateArgs>(args: Prisma.Subset<T, Supplier_groupsAggregateArgs>): Prisma.PrismaPromise<GetSupplier_groupsAggregateType<T>>

  /**
   * Group by Supplier_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {supplier_groupsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends supplier_groupsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: supplier_groupsGroupByArgs['orderBy'] }
      : { orderBy?: supplier_groupsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, supplier_groupsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSupplier_groupsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the supplier_groups model
 */
readonly fields: supplier_groupsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for supplier_groups.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__supplier_groupsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  suppliers<T extends Prisma.supplier_groups$suppliersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.supplier_groups$suppliersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$suppliersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the supplier_groups model
 */
export interface supplier_groupsFieldRefs {
  readonly id: Prisma.FieldRef<"supplier_groups", 'Int'>
  readonly group_code: Prisma.FieldRef<"supplier_groups", 'String'>
  readonly group_name: Prisma.FieldRef<"supplier_groups", 'String'>
  readonly description: Prisma.FieldRef<"supplier_groups", 'String'>
  readonly created_at: Prisma.FieldRef<"supplier_groups", 'DateTime'>
}
    

// Custom InputTypes
/**
 * supplier_groups findUnique
 */
export type supplier_groupsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * Filter, which supplier_groups to fetch.
   */
  where: Prisma.supplier_groupsWhereUniqueInput
}

/**
 * supplier_groups findUniqueOrThrow
 */
export type supplier_groupsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * Filter, which supplier_groups to fetch.
   */
  where: Prisma.supplier_groupsWhereUniqueInput
}

/**
 * supplier_groups findFirst
 */
export type supplier_groupsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * Filter, which supplier_groups to fetch.
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of supplier_groups to fetch.
   */
  orderBy?: Prisma.supplier_groupsOrderByWithRelationInput | Prisma.supplier_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for supplier_groups.
   */
  cursor?: Prisma.supplier_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` supplier_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` supplier_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of supplier_groups.
   */
  distinct?: Prisma.Supplier_groupsScalarFieldEnum | Prisma.Supplier_groupsScalarFieldEnum[]
}

/**
 * supplier_groups findFirstOrThrow
 */
export type supplier_groupsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * Filter, which supplier_groups to fetch.
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of supplier_groups to fetch.
   */
  orderBy?: Prisma.supplier_groupsOrderByWithRelationInput | Prisma.supplier_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for supplier_groups.
   */
  cursor?: Prisma.supplier_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` supplier_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` supplier_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of supplier_groups.
   */
  distinct?: Prisma.Supplier_groupsScalarFieldEnum | Prisma.Supplier_groupsScalarFieldEnum[]
}

/**
 * supplier_groups findMany
 */
export type supplier_groupsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * Filter, which supplier_groups to fetch.
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of supplier_groups to fetch.
   */
  orderBy?: Prisma.supplier_groupsOrderByWithRelationInput | Prisma.supplier_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing supplier_groups.
   */
  cursor?: Prisma.supplier_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` supplier_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` supplier_groups.
   */
  skip?: number
  distinct?: Prisma.Supplier_groupsScalarFieldEnum | Prisma.Supplier_groupsScalarFieldEnum[]
}

/**
 * supplier_groups create
 */
export type supplier_groupsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * The data needed to create a supplier_groups.
   */
  data: Prisma.XOR<Prisma.supplier_groupsCreateInput, Prisma.supplier_groupsUncheckedCreateInput>
}

/**
 * supplier_groups createMany
 */
export type supplier_groupsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many supplier_groups.
   */
  data: Prisma.supplier_groupsCreateManyInput | Prisma.supplier_groupsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * supplier_groups createManyAndReturn
 */
export type supplier_groupsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * The data used to create many supplier_groups.
   */
  data: Prisma.supplier_groupsCreateManyInput | Prisma.supplier_groupsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * supplier_groups update
 */
export type supplier_groupsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * The data needed to update a supplier_groups.
   */
  data: Prisma.XOR<Prisma.supplier_groupsUpdateInput, Prisma.supplier_groupsUncheckedUpdateInput>
  /**
   * Choose, which supplier_groups to update.
   */
  where: Prisma.supplier_groupsWhereUniqueInput
}

/**
 * supplier_groups updateMany
 */
export type supplier_groupsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update supplier_groups.
   */
  data: Prisma.XOR<Prisma.supplier_groupsUpdateManyMutationInput, Prisma.supplier_groupsUncheckedUpdateManyInput>
  /**
   * Filter which supplier_groups to update
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * Limit how many supplier_groups to update.
   */
  limit?: number
}

/**
 * supplier_groups updateManyAndReturn
 */
export type supplier_groupsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * The data used to update supplier_groups.
   */
  data: Prisma.XOR<Prisma.supplier_groupsUpdateManyMutationInput, Prisma.supplier_groupsUncheckedUpdateManyInput>
  /**
   * Filter which supplier_groups to update
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * Limit how many supplier_groups to update.
   */
  limit?: number
}

/**
 * supplier_groups upsert
 */
export type supplier_groupsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * The filter to search for the supplier_groups to update in case it exists.
   */
  where: Prisma.supplier_groupsWhereUniqueInput
  /**
   * In case the supplier_groups found by the `where` argument doesn't exist, create a new supplier_groups with this data.
   */
  create: Prisma.XOR<Prisma.supplier_groupsCreateInput, Prisma.supplier_groupsUncheckedCreateInput>
  /**
   * In case the supplier_groups was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.supplier_groupsUpdateInput, Prisma.supplier_groupsUncheckedUpdateInput>
}

/**
 * supplier_groups delete
 */
export type supplier_groupsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
  /**
   * Filter which supplier_groups to delete.
   */
  where: Prisma.supplier_groupsWhereUniqueInput
}

/**
 * supplier_groups deleteMany
 */
export type supplier_groupsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which supplier_groups to delete
   */
  where?: Prisma.supplier_groupsWhereInput
  /**
   * Limit how many supplier_groups to delete.
   */
  limit?: number
}

/**
 * supplier_groups.suppliers
 */
export type supplier_groups$suppliersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the suppliers
   */
  select?: Prisma.suppliersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the suppliers
   */
  omit?: Prisma.suppliersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.suppliersInclude<ExtArgs> | null
  where?: Prisma.suppliersWhereInput
  orderBy?: Prisma.suppliersOrderByWithRelationInput | Prisma.suppliersOrderByWithRelationInput[]
  cursor?: Prisma.suppliersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SuppliersScalarFieldEnum | Prisma.SuppliersScalarFieldEnum[]
}

/**
 * supplier_groups without action
 */
export type supplier_groupsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the supplier_groups
   */
  select?: Prisma.supplier_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the supplier_groups
   */
  omit?: Prisma.supplier_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.supplier_groupsInclude<ExtArgs> | null
}
